### ISSUE TITLE
[BUG]Do Not Have Rights to Edit Chunk

### ISSUE THREAD

**Issue by youyoulyz** [IridiumLLC/IridiumSkyblock#103]
According to this video, 
[http://mcyouyou.f3322.net:233/res/Minecraft_%201.15.2%20-%20%E5%A4%9A%E4%BA%BA%E6%B8%B8%E6%88%8F%EF%BC%88%E7%AC%AC%E4%B8%89%E6%96%B9%EF%BC%89%202020-05-03%2015-18-59.mp4](url)
I am an op of a server using this plugin. (2.3.6)
I join an island.
I have the right to operate on other chunks.
But I cannot operate on the only region.
Only if I issue the op-command"/is bypass" can I edit the chunk.
But if I issue "/is bypass", I cannot edit the chunk again.
Hope you will solve the problem.

**Comment by IridiumLLC** [comment]
update
