### ISSUE TITLE
[BUG]Do not permitted to do anything

### ISSUE THREAD

**Issue by huzpsb** [IridiumLLC/IridiumSkyblock#104]
**Describe the bug**
Anyone isn't permitted to do anything.

**Screenshots**

![TIM截图20200504182827](https://user-images.githubusercontent.com/41772578/80957054-f9495e00-8e34-11ea-88a3-bfc85d8cf581.png)

**Comment by IridiumLLC** [comment]
this is probabbly because you edited commands.json and made the commands require permissions. send your commands.json via pastebin. Also assuming your the same person who made the review on the plugin, id appreciate if you deleted that as reviews arnt the place to do support

**Comment by huzpsb** [comment]
I had tried DELETE command.yml and it didn't work.
I will change it into 5-stars as soon as the problem is solved.

**Comment by huzpsb** [comment]
well after updating to2.3.9,the problem is gone
thank you bro!
(and I'v changed into 5-stars
(and In China Google,twitter,link-ed in,discord,facebook,telegram,skype and many thing else won't work

**Comment by huzpsb** [comment]
Problem solved
