### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Alv5ro** [IridiumLLC/IridiumSkyblock#107]
In the missions part of the wiki it says...
"NOTE: By default, Missions are set to restart Daily in config.json. (Near line 32 - "missionRestart": "Daily",) This can be changed to Instantly, if you wish."
Could you also add what the other options are, if it hasn't been added in the plugin yet, could you add weekly, monthly and yearly.
Thanks

**Comment by IridiumLLC** [comment]
The wiki is available for anyone to edit, if you think something is missing feel free to add it :)
