### ISSUE TITLE
Command: /is setvisit [SUGGESTION]

### ISSUE THREAD

**Issue by Playergamehd** [IridiumLLC/IridiumSkyblock#108]
Hello,
I have a Suggestion:
The /is setvisit Command (command can be changed)

-What it does?
It simply sets a Point where a Visitor spawns if they make /is visit.

- Why is it helpful?
Normaly the Visitor gets teleported to the Home from the Island
but with this Command you can seperate this and don´t have to
build a way into your private House or so.

Bye

**Comment by IridiumLLC** [comment]
I wont be implementing this
