### ISSUE TITLE
[WELCOME] SIGN WARP [SUGGESTION]

### ISSUE THREAD

**Issue by Tashaanapixel** [IridiumLLC/IridiumSkyblock#109]
**Describe the Suggestion**
[REMEMBER NEW/RESET ISLAND ALWAYS HAVE [WELCOME] SIGN ON IT]

THE PLAYERS CAN WARP ON YOUR ISLAND BY PUTTING A [WELCOME] SIGN ANYWHERE IN YOUR ISLAND FOR EXAMPLE.
When they type the command ./is warp xScenery They will warp where you put your [WELCOME] sign unless you put it on your island but if there is no [WELCOME] sign in your island they can't warp to your island, and if you have already [WELCOME] sign and you made another [WELCOME] sign the other one will be automatically remove or it will be inactive warp.

I'll REPEAT IT SO YOU CAN UNDERSTAND IT [WITH PICTURES]

THIS IS THE PICTURE WHEN YOUR [WELCOME] SIGN IS ACTIVE!

![2020-05-11_19 46 07](https://user-images.githubusercontent.com/64865982/81558345-1bf0ef00-93c0-11ea-96ee-ba7b0ab0b09f.png)

THIS IS THE PICTURE OF INACTIVE [WELCOME] SIGN, THIS HAPPENS WHEN YOU PLACE ANOTHER [WELCOME] SIGN IF YOU HAVE ALREADY [WELCOME] SIGN IN YOUR ISLAND. IT WOULD AUTOMATICALLY BE INACTIVE/REMOVE. ( PLAYERS CAN'T WARP HERE ANYMORE AND WILL WARP TO NEW [WELCOME] SIGN.

![2020-05-11_19 46 14](https://user-images.githubusercontent.com/64865982/81558550-7722e180-93c0-11ea-9aae-e48df53dd026.png)

Lastly If you don't have welcome sign on your island, Players can't warp to your island.
Thats it !

[REMEMBER NEW/RESET ISLAND WILL ALWAYS HAVE [WELCOME] SIGN and it's up to them if they will remove or place it to a new place.]

- xScenery

**Comment by IridiumLLC** [comment]
I dont like this suggestion, If you dont want people to visit your island you can always do /is private
