### ISSUE TITLE
[BUG] Can access to other worlds causing explot

### ISSUE THREAD

**Issue by SmexyDuk** [IridiumLLC/IridiumSkyblock#111]
**Describe the bug**
Title says it all, whenever you go to a different world (I'm not using bungee, i am running everything on one server) you can access the GUI and all that, withdraw skyblock money and transfer it to another world which is for example "FACTIONS". Is there a way to block such commands or one permission to disallow access to /is command? I haven't found the permissions list anywhere.

**To Reproduce**
/is on a different world

**Screenshots**
none

**Comment by IridiumLLC** [comment]
And thats why you use bungee?

**Comment by SmexyDuk** [comment]
I dont use bungee, I only use Multiverse. Only Issue I'm having is that theres no global permission for all the commands. What I did was add it all in manually 1by1 per command. though they can still access /is but cannot access the commands inside the /is GUI. Which I think solves this issue, but it's all spammed and cluttered up the groups. Would be nice if there's one for all commands.

**Comment by MrMathias154** [comment]
Its for why we generally separate server with differents games ...

**Comment by IridiumLLC** [comment]
> I dont use bungee, I only use Multiverse.
Which is why your having these issues?

**Comment by SmexyDuk** [comment]
Yup, its because the plugin runs only on 1 server, thats why every single world the server has are able to access the command.

**Comment by IridiumLLC** [comment]
Dude this plugin isnt designed to work like that, just get bungee
