### ISSUE TITLE
[BUG] Spike on delete

### ISSUE THREAD

**Issue by MrMathias154** [IridiumLLC/IridiumSkyblock#112]
**Describe the bug**
Spike lag when user confirm the delete of an island

**To Reproduce**
1. Go to your is (/is create | /is home)
2. delete your island (/is delete)
3. Confirm yes in the gui
4. See Spike / tps drop

Timings :
https://timings.aikar.co/?id=c8d1c1ae9bc543b5986abdfbe94a6bc2

Sky Config:
config.json: https://p.pegas.fun/xayikihejo.json
upgrades.json: https://p.pegas.fun/likikoqefi.json

And nothings to see in log

Why you don't use WE/FAWE for deleting island ?

**Comment by IridiumLLC** [comment]
weird, I Optimised /is delete in the latest version. Install [spark](https://www.spigotmc.org/resources/spark.57242/) then do /spark sampler --only-ticks-over 70 then delete the island and do /spark sampler --stop and send me the link

**Comment by IridiumLLC** [comment]
@MrMathias154
