### ISSUE TITLE
[BUG] Challenge "Break ores" bugged

### ISSUE THREAD

**Issue by TheRobLP** [IridiumLLC/IridiumSkyblock#115]
**Describe the bug**
The mission "Mine 50 ores" can not be completed
**To Reproduce**
1. Mine some ores
2. Do /is missions and hover over the Miner mission
3. No progress was made, apparently

**Screenshots**

**Comment by IridiumLLC** [comment]
theres most likely an issue in your missions.json try updating to latest version deleting missions.json and letting it regenerate
