### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by zManuu** [IridiumLLC/IridiumSkyblock#119]
Could you please add Database (like MySQL or MariaDB) Support to the Plugin. On my Server, The Plugin generates some lagg, which, I think, is caused by the fact, that the plugin uses files.
Super plugin, thats the only thing thats missing :D

**Comment by IridiumLLC** [comment]
Unfortunatly my knowledge for MySQL is very limited, However someone has offered to create a pullrequest to add support for this.

**Comment by zManuu** [comment]
We would love it so much, even more as just now! SQL would work as well of course, it just needs to be some type of database :D
