### ISSUE TITLE
[SUGGESTION] WildStacker Barrels

### ISSUE THREAD

**Issue by mzuber6** [IridiumLLC/IridiumSkyblock#121]
Add support for WildStacker barrels. There is only support for the spawners currently.

This is the barrel part of the api.
https://github.com/OmerBenGera/WildStackerAPI/blob/master/src/main/java/com/bgsoftware/wildstacker/api/objects/StackedBarrel.java

**Comment by IridiumLLC** [comment]
I intend to add my own blockstacking to this plugin, so I wont be implementing this
