### ISSUE TITLE
[BUG] Island regen issue with UltimateStacker

### ISSUE THREAD

**Issue by HakanGulgen** [IridiumLLC/IridiumSkyblock#124]
**Describe the bug**
- UltimateStacker's spawner holograms stays after island regen command.
- Suggestion: Plugin should teleport player to main spawn after regen to prevent chunk issue.

**To Reproduce**
1. /is regen

**Screenshots**
![unknown](https://user-images.githubusercontent.com/20889640/85060911-a8a47f00-b1ae-11ea-9734-4643cea57a06.png)

**Comment by MertUnverdi** [comment]
Dostum, biliyorum geç oldu görmemişim.
Bu sorun 1.8 in nmsi ile alakalı olduğunu düşünüyorum.
Dediğin gibi spawna gönderme mantığı olabilir. Fakat bunu api ile kendiniz yapmalısınız. Çünkü plugin multiversion ve diğer sürümlerde geçerli olan bi durum değil..
