### ISSUE TITLE
[BUG] Weird numbers in island value counting

### ISSUE THREAD

**Issue by tabl3** [IridiumLLC/IridiumSkyblock#125]
**Describe the bug**
I don't even know how to describe it, probably same as the title - **Weird numbers in island value counting**. Just look at the pictures below.
Minecraft server version is 1.15.2, plugin version 2.4.2, no errors in console.

**To Reproduce**
1. Go to 'blockvalues.json'
2. Edit any block to value 0.1
3. Create island, place block by block and check /is value

**Screenshots**
![bugreportskyblock](https://user-images.githubusercontent.com/47261611/85119174-a6c7d380-b221-11ea-8376-c6c4d785413e.PNG)
![bugreportskyblock2](https://user-images.githubusercontent.com/47261611/85119176-a7606a00-b221-11ea-854c-39049e01dfcd.png)

**Hotfix**
Add opition to see just certain amount of numbers after the decimal point.

**Comment by IridiumLLC** [comment]
Weird, Ill look into this
