### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DukeOfDerp77** [IridiumLLC/IridiumSkyblock#129]
**Describe the bug**
Using jetminions, I open the iridium skyblock shop, but if I click a slot a minion would be, it buys the minions

**To Reproduce**
1. Open skyblock shop
2. Click a slot a minion is in

**Comment by IridiumLLC** [comment]
Not quite sure I understand? Could you include video's/pictures? Also Ill probabbly need your shop config files

**Comment by DukeOfDerp77** [comment]
Hey sorry. GUI names were the same. Changing it fixes it!
