### ISSUE TITLE
[BUG] Water flow off the board

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#130]
**Describe the bug**
If you put water in the island board this flow off the board and if you regen the island the water continue off the board. (I'm using Spigot 1.8.8).

**Screenshots**
![image](https://user-images.githubusercontent.com/66755751/85250357-b5cea180-b42c-11ea-9ca9-ba6536e15ff2.png)

![image](https://user-images.githubusercontent.com/66755751/85250452-f9291000-b42c-11ea-86ef-ba670340bfd1.png)

**Comment by IridiumLLC** [comment]
Are you using the latest plugin version? I fixed this issue ages ago
