### ISSUE TITLE
[BUG] Money duplication

### ISSUE THREAD

**Issue by Spildunky** [IridiumLLC/IridiumSkyblock#134]
**Describe the bug**
On rare occasions you're able to deposit money into the island bank but not have any money withdrawn from your balance, therefore creating an infinite amount of money so long as you sit there are click away with depositing. Just to go over it again, this happens randomly and I cannot find a way to reproduce this efficiently but sometimes when you go to deposit into the island bank your balance does not change but your bank balance goes up, allowing you to deposit an infinite amount of money and withdraw it all when you're satisfied.

**To Reproduce**
This is random but this is how to reproduce:
Open island bank, 
Deposit cash,
Money is not taken from balance but bank balance goes up,
Withdraw money once satisfied and you're not able to do it again until this random bug occurs again.
Server Version: 1.15.2
Plugin version: 2.4.3

**Comment by MertUnverdi** [comment]
if still have this issue please comment and join our discord server:
https://discord.gg/PTpg4fD
if already fixed please close your issue <3
