### ISSUE TITLE
[BUG] Failed to Parse islandmanager.json 

### ISSUE THREAD

**Issue by Laotouy** [IridiumLLC/IridiumSkyblock#137]
<img width="1441" alt="1" src="https://user-images.githubusercontent.com/48210313/86027262-12e8d980-ba63-11ea-9555-5860ff7da4dc.png">

**Comment by Laotouy** [comment]
Duplicate keys appear in islandCache

**Comment by Seliba** [comment]
How can the problem be reproduced? In my case, this category is not reproducible in a new installation nor an old one.

**Comment by Erorserv** [comment]
I found this to be a problem with Java 11. Switching to Java 8 fixed it for me.
