### ISSUE TITLE
[BUG] IS BANK withdrawing and depositing glitch

### ISSUE THREAD

**Issue by Alv5ro** [IridiumLLC/IridiumSkyblock#143]
**Describe the bug**
There's a glitch in the latest version (2.4.4) where depositing and withdrawing island crystals is messed up. When taking out crystals, it takes out only 1, but in the GUI it says that they are all taken out. I've just realised that this might not be a bug, however it looks like one because there's no way I can tell how many crystals I have in my hand which we find is confusing. 

If this isn't a bug I'd like to suggest that either
1. When people withdraw, their should be an option saying how much they want to take out, if this exceeds the inventory space, it says that it can't do it for that reason.
2. Disable Island crystal withdrawal, I personally believe that noone should be able to take it out because high level players can boost low level players for free, other than giving other people crystals, I don't know why people would take it out. Just like in real money, you don't take money out unless you're paying people.
3. Introduce /is crystals pay (username) (amount) and do the 2nd suggestion.

**To Reproduce**
I made a video of my friend doing it that shows how he did it. https://drive.google.com/file/d/1RUKyxvlnHR7l3H2iL9ZegD0bL67e5VF8/view?usp=sharing

If you need anything else let me know!

**Comment by IridiumLLC** [comment]
Sorry about the late reply, This is a new feature. I recomend you make this change in your inventories.json

```
  "crystals": {
    "material": "NETHER_STAR",
    "amount": 1,
    "title": "&b&lIsland Crystals",
    "lore": [
      "&7{crystals} Crystals",
      "&b&l[!] &bLeft click to withdraw",
      "&b&l[!] &bRight click to deposit"
    ],
    "slot": 13
  },
```
