### ISSUE TITLE
[BUG]/Is gui doesn't show

### ISSUE THREAD

**Issue by Alv5ro** [IridiumLLC/IridiumSkyblock#144]
**Describe the bug**
The '/is' gui shows a few items rather than the ones I set. This worked fine on other versions, but not on the latest. The items that are missing are still clickable and do their function, I just can't see what they do.

**To Reproduce**
1. do /is

**Screenshots**
Here is what it looked like on other versions:
https://imgur.com/a/Kav50U1
And on the version 2.4.4:
https://imgur.com/a/eDGa2mX

**Comment by IridiumLLC** [comment]
Any errors in console? Also can I have your inventories.json?

**Comment by Alv5ro** [comment]
Inverntories.json: https://pastebin.com/2vHuQN22
console: https://pastebin.com/DmEjS32X

**Comment by Alv5ro** [comment]
I've replaced the inventories.json with a backup where it was working, and it didn't work there. I also tried that with the version 2.4.2 which worked before and doesn't anymore.

**Comment by Alv5ro** [comment]
I deleted the inventories.json file so a fresh one would be made, and this happened: https://imgur.com/a/EWpx2aB
This is the error I get: https://pastebin.com/xLGMWYvr

**Comment by Alv5ro** [comment]
I've removed every file except the island manage, backups and schematics, then on the reset, this is what the gui looks like (on 2.4.4): https://imgur.com/a/Bl30eRe and this is the error: https://pastebin.com/GnmtpZ2S

**Comment by Alv5ro** [comment]
I also found from help from people at the paper discord:
![image](https://user-images.githubusercontent.com/57922931/86484075-47071780-bd4d-11ea-9baf-be8f382b62ab.png)
I removed every iridium skyblock file, and it the problem still occured.

**Comment by Alv5ro** [comment]
i fixed the issue, the version of paper had a bug "Player Profile textures being duplicated" I believe that was the issue.
