### ISSUE TITLE
[BUG]/tpa or /back or /tp etc to an island that you're already on

### ISSUE THREAD

**Issue by Alv5ro** [IridiumLLC/IridiumSkyblock#145]
**Describe the bug**
Not a major bug. When you do any of those commands, on another island to the same island, it says that you're visiting the island, even though you're already on that island

**To Reproduce**
1. /tpa to another island. tpa again to the same island

**Screenshots**
https://imgur.com/a/P2mZVKC

**Comment by IridiumLLC** [comment]
Already fixed this in beta-versions
