### ISSUE TITLE
[BUG] Islands aren't centered

### ISSUE THREAD

**Issue by Alv5ro** [IridiumLLC/IridiumSkyblock#146]
**Describe the bug**
When creating a new island, the island generates non centrally

**To Reproduce**
create an island

**Screenshots**
https://imgur.com/a/Y8Ta5Zz
This was used in the 2.4.4. I'm now using 2.4.3 because island creation works fine there

**Comment by Alv5ro** [comment]
I can confirm that this is still an issue on version 2.4.5

**Comment by IridiumLLC** [comment]
Send me your island schematic please, i believe this is an issue on your end

**Comment by Alv5ro** [comment]
I'll send you the schematic over discord (I'm Alv5ro#0394), I've followed these steps which I added on the [github FAQ](https://github.com/IridiumLLC/IridiumSkyblock/wiki/FAQ#add-schematics). 

Here is my schematic.json [https://pastebin.com/i4WWnFPB](https://pastebin.com/i4WWnFPB)

**Comment by Alv5ro** [comment]
The github FAQ question I'm referring to is Q: How do I align my island with the island border?

**Comment by IridiumLLC** [comment]
I removed the FAQ section on the wiki as it suggests doing the exact opposite of what I would suggest. In reality the plugin will center the schematic automatically, but it cant differentiate between actual blocks and air blocks, so if you create the schematic with loads of air blocks on one side it will center it with the air blocks included which will make it off centered.

Im not very good at explaining stuff, but you basically have to make the schematic area as small as possible and it should fix your issue
