### ISSUE TITLE
[BUG] Permissions

### ISSUE THREAD

**Issue by ToxicGR** [IridiumLLC/IridiumSkyblock#149]
In the wiki ( https://github.com/IridiumLLC/IridiumSkyblock/wiki/Commands-and-Permissions ) you say for example that the permission is for giving crystals "iridiumskyblock.givecrystals". But when the default commands.json generates the permission note is "givecystals". The result the permission doesn't work. you have to go and manually change it to "iridiumskyblock.givecrystals" and also that's not the only issue. After changing some permission notes it still doesn't work for all of them for example I made /is admin with the permission iridiumskyblock.admin ( in the commands.json ) and still doesn't let me do /is admin.

**Comment by Seliba** [comment]
> also that's not the only issue. After changing some permission notes it still doesn't work for all of them for example I made /is admin with the permission iridiumskyblock.admin ( in the commands.json ) and still doesn't let me do /is admin.
This works for me, have you written the permission correctly and are you using the latest version of IridiumSkyblock?

> In the wiki ( https://github.com/IridiumLLC/IridiumSkyblock/wiki/Commands-and-Permissions ) you say for example that the permission is for giving crystals "iridiumskyblock.givecrystals". But when the default commands.json generates the permission note is "givecystals". The result the permission doesn't work. you have to go and manually change it to "iridiumskyblock.givecrystals" 
Yep, that's definitely an issue

**Comment by ToxicGR** [comment]
The latest version of iridum skyblock gives me issues with the island top. It doesn't work at all for me

**Comment by IridiumLLC** [comment]
Fixed in latest commit
