### ISSUE TITLE
[BUG] FREEZE SERVER

### ISSUE THREAD

**Issue by Thin-Troll** [IridiumLLC/IridiumSkyblock#150]
**Describe the bug**
When the ISB collects more than 500 islands, SERVER DELAYS begin .. the server stops responding to commands, with TPS 19.9
It seems that ISB processes islands for a long time and creates a heavy load, but the server itself does not lag, everything affects the response of the teams and the game as a whole.
with your assistant from the discord, we came to the conclusion that this JSON does not withstand such a number of islands (such a file size) and begins to be processed for a long time.
When I delete the islandmanager.json file, the lag problem completely disappears. but wipe every 1.5 weeks is not an option.
Also, after rebooting the server, for some time it works adequately, but in a couple of hours it comes to the fact that it is impossible to write even commands, the server stops responding to them.

At the moment, at least make the removal of the old island (/ is purge)
but generally change the storage system (preferably mysql, but maybe now yaml will do)

**To Reproduce**
1. Generate more than 500-700 islands (file weight islandmanager.json - 2mb+ )
2. Let the players play on the server, use ISB to use the plug-in (teleport, buy, create islands)
3. Watch server lags, other plugins stop working somehow, you cannot log into the server ..
commands like ISB and other plug-ins cease to respond either .. (watch the video, in the last seconds I write commands, the server does not give any reaction)

**Screenshots**
All files and video demo -
https://cloud.mail.ru/public/5pKj/5apBnwxPW

**Comment by Thin-Troll** [comment]
https://timings.aikar.co/?id=fbea3bf934e9473ca9a121fc0f639192

**Comment by Thin-Troll** [comment]
Version ISB - 2.4.4

**Comment by IridiumLLC** [comment]
Ill look into this

**Comment by Thin-Troll** [comment]
?

**Comment by Thin-Troll** [comment]
once again faced this problem.
Exceeded over 700 islands again and the friezes began.
Commands cannot be entered, chat does not work.

**Comment by Thin-Troll** [comment]
up
