### ISSUE TITLE
[BUG] Visiting island message spam.

### ISSUE THREAD

**Issue by Sybsuper** [IridiumLLC/IridiumSkyblock#152]
**Describe the bug**
When you are visiting an island, and you teleport within that island, the owner of that island and the visiting player will see the message that someone is visiting their island or that they are visiting someone's island. This should of course only happens when they visit it, not if they are already on the other player's island.

**To Reproduce**
1. Get player A and player B on your server and let them make an island.
2. Tell player A to visit player B's island.
3. Now the text will display that player A is visiting player B's island. Which it should of course.
4. Now player A does something that makes him get teleported to the island that he is visiting, for example teleport to player B or stand inside the cobblestone generator (if a block is pushed inside the bottom half of the player he will be teleported onto the block) or mine the block you are standing on (this too will glitch you inside the block for a short time, until the server teleports you on top of the block).
5. The message will again appear, while the player was already visiting the island.

**Solution**
Add an extra if statement in the onPlayerTeleport Listener, that checks if the player's `event.getFrom()` location isn't on the same island as the island at the `event.getTo()` location.

```java
// Already existing code in the com.iridium.iridiumskyblock.listeners.PlayerTeleportListener.java file. Line: 16-21
Location toLocation = event.getTo();
IslandManager islandManager = IridiumSkyblock.getIslandManager();
Island island = islandManager.getIslandViaLocation(toLocation);
if (island == null) {
  return;
}
// Start extra code
// Try to get the island where the player teleported from.
Island fromIsland = islandManager.getIslandViaLocation(event.getFrom());
// Check if the island exists, and if it exists check if it is the same island where the player is teleporting to.
if (fromIsland != null && fromIsland.getId() == island.getId()) {
  // In that case: Don't do anything.
  return;
}
```

**Comment by Sybsuper** [comment]
Version: 2.4.4

**Comment by IridiumLLC** [comment]
This already exists in the beta-versions
https://github.com/IridiumLLC/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/listeners/PlayerTeleportListener.java#L27

**Comment by Sybsuper** [comment]
Then why isn't this fix released yet? I mean, many servers must be having this issue and it can be really annoying if the players know how to use this bug, which isn't that hard to figure out.

**Comment by IridiumLLC** [comment]
`Then why isn't this fix released yet?` You expect me to post it to spigot every time I fix something? That means that some days the plugin will get around 20 updates a day. I do updates to spigot every monday

**Comment by Sybsuper** [comment]
That's true, I just thought this issue would be worth an extra update. It can be annoying especially for bigger servers, with an anti-cheat. Of course, I understand you can't release an update for every little bug fix or addition, that would be a waste of time. Thanks for the great plugin!
