### ISSUE TITLE
[BUG] Crystals withdraw

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#154]
**Describe the bug**
When i withdraw a crystal if i have most than 1 crystals in bank i only earn one

**To Reproduce**

**Screenshots**

**Comment by IridiumLLC** [comment]
huh?

**Comment by Seliba** [comment]
I believe this is a new feature in IridiumSkyblock. Crystals are now all stored in one item, which means that one crystal can be worth more. However, as a player you can't see the value of a crystal item, this has to be fixed @IridiumLLC

**Comment by IridiumLLC** [comment]
`There is also no backwards compatibility, crystals withdrawn before the update can no longer be deposited and are worthless.` Ye, Ive been wanting to make this change for a while now, and that was one of my main concerns, but I figured id just do it anyway xD

Its recomended to make this change to your inventories.json
```
  "crystals": {
    "material": "NETHER_STAR",
    "amount": 1,
    "title": "&b&lIsland Crystals",
    "lore": [
      "&7{crystals} Crystals",
      "&b&l[!] &bLeft click to withdraw",
      "&b&l[!] &bRight click to deposit"
    ],
    "slot": 13
  },
```
