### ISSUE TITLE
Items in chest dont spawn

### ISSUE THREAD

**Issue by LilToad** [IridiumLLC/IridiumSkyblock#163]
when an island is created there is nothing in the chest.

**Comment by Seliba** [comment]
That should be a problem with your island schematic

**Comment by IridiumLLC** [comment]
I belive its an issue with worldedit and 1.8 schematics. If your using a worldedit for 1.13+ with a 1.8 schematic (which the default is) then for some reason items in the chest wont be there. Just recreate the schematic with your version of worldedit

**Comment by LilToad** [comment]
may i ask, how do i recreate the schematic with worldedit?

**Comment by LilToad** [comment]
@IridiumLLC
