### ISSUE TITLE
[BUG] Errors in the console when someone place a block

### ISSUE THREAD

**Issue by Gracv** [IridiumLLC/IridiumSkyblock#169]
**Describe the bug**
There are errors in the console when someone place a block anywhere

**To Reproduce**
1. Take any block
2. Place a block
3. See error

**Screenshots**
I think log is better than just screenshot https://paste.gg/p/anonymous/8ade4ff4ff3b4ecfa088d10e0b13eaca

Plugin version: 2.4.5
Minecraft version: 1.16.1

**Comment by Gracv** [comment]
Plugin version: 2.4.5

**Comment by YahBoyTUGG** [comment]
Issue was already fixed in a commit, wait for a monday release or compile the code.
