### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VARboosted** [IridiumLLC/IridiumSkyblock#170]
**Describe the bug**
FIRST BUG: if you do /is bank and then left click you get Max xp (21,863 Experience) please fix this as fast as possible it’s a huge bug.

SECOND BUG: is value dont go up for some players 

tried 2.4.5 version, lastest build, 2.4.4..
version 1.8.8 spigot

**Comment by Seliba** [comment]
I can't reproduce any of the issues on the latest build

**Comment by vasquezfr15** [comment]
I have a problem in the latest version. By putting / is or / is create, I start sending the island of creation message in the chat infinite times. then the server shuts down. Is it a plugin or a compatibility issue?

**Comment by Seliba** [comment]
If I remember correctly this error was fixed a few days ago, the update should be coming Monday on SpigotMC

**Comment by VARboosted** [comment]
> If I remember correctly this error was fixed a few days ago, the update should be coming Monday on SpigotMC. It is caused by using FAWE instead of the normal Worldedit

i'm using normal worldedit and how it is worldedit? it is /is bank and /is value

**Comment by Seliba** [comment]
> i'm using normal worldedit and how it is worldedit? it is /is bank and /is value

This was an reply to @vasquezfr15, I have no idea why he replied to this issue with his own issue
