### ISSUE TITLE
[BUG] not support .schem format in 1.13 or upper

### ISSUE THREAD

**Issue by ZacharyMSL** [IridiumLLC/IridiumSkyblock#172]
https://cdn.discordapp.com/attachments/592092308514537510/731522371990716526/unknown.png

.schematic format just support to 1.12.2 version , in 1.13 or upper , building will save as .schem format . so it looks like this plugin do not support with .schem as island building

**Comment by LilToad** [comment]
yeah i have same issue

**Comment by Erorserv** [comment]
I had this issue, but updating to the latest beta version of WorldEdit fixed it.
