### ISSUE TITLE
[SUGGESTION] add custom model data in GUI items

### ISSUE THREAD

**Issue by ZacharyMSL** [IridiumLLC/IridiumSkyblock#174]
in 1.14 version update , there has a item NBT called custom-model-data just updated . it can change item's model or texture with this nbt data . but this feature seems not on IridiumSkyblock plugin . So hope you may update it ~ thx

**Comment by IridiumLLC** [comment]
how is this different from #173 ?

**Comment by IridiumLLC** [comment]
ok, im going to assume nothing so im closing this
