### ISSUE TITLE
[BUG] at com.iridium.iridiumskyblock.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:56)

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#175]
When I place a block outside the world of the islands it says that on my console

**To Reproduce**
> [15:40:51 WARN]: java.lang.NullPointerException
> [15:40:51 WARN]: at com.iridium.iridiumskyblock.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:56)
> [15:40:51 WARN]: at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
> [15:40:51 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15:40:51 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [15:40:51 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> [15:40:51 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [15:40:51 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [15:40:51 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> [15:40:51 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> [15:40:51 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:160)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [15:40:51 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:40:51 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [15:40:51 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [15:40:51 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:40:58 WARN]: java.lang.NullPointerException
> [15:40:58 WARN]: at com.iridium.iridiumskyblock.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:56)
> [15:40:58 WARN]: at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
> [15:40:58 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [15:40:58 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [15:40:58 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> [15:40:58 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [15:40:58 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [15:40:58 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> [15:40:58 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> [15:40:58 WARN]: at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:160)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [15:40:58 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [15:40:58 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [15:40:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [15:40:58 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by IridiumLLC** [comment]
Already been fixed, Will be out on spigot monday
