### ISSUE TITLE
[BUG] /is top does not refresh upon changing blockValues

### ISSUE THREAD

**Issue by tabernacle8** [IridiumLLC/IridiumSkyblock#176]
**Describe the bug**

**Observed:** /is top does not actively refresh. It appears to add to an island level once a block of value is placed but does not re-calculate the island level periodically. This makes changes to blockValues ultimately useless for old islands.

**Theory:** Once a block of value is placed on an island, a handler adds it's block value to your island value. This works, but does not take into account if a block is deleted, moved, or it's value is changed. Therefore, island top cannot actively refresh and only works going forward.

**Possible resolution:** Unknown.

**To Reproduce**
1. Create an island (Fresh install of everything, do not change configs)
2. Place lots of emerald, diamond, and gold blocks down on your island
3. Check your value in /is top
4. Change values of all blocks to something very low (Such as 0) in blockValues
5. Restart Server
6. /is top has not updated with new block values. It still calculates island level as if blockValues was not changed

NOTE: **Blocks of value placed on an island, after blockValues has changed, do work properly for /is top. The problem lies within old blocks not being recalculated**

**Screenshots**
Note that Aura has way more blocks, but Maxx is still in the lead because his blocks were placed when blockValues were high and Aura placed his blocks when blockValues were lowered

Running /is value for both players returns the same number as displayed on /is top. How can that be though? Aura has way more stuff. In fact, the true value for Aura's island is so far away from 200 it makes no sense.

![image](https://user-images.githubusercontent.com/19417482/87252047-fa929a80-c424-11ea-9bf3-4d4a687198d9.png)
![image](https://user-images.githubusercontent.com/19417482/87252050-08482000-c425-11ea-9dda-a973339f8012.png)

**Original Block Values: Default**
**New Block Values:**
![image](https://user-images.githubusercontent.com/19417482/87252211-12b6e980-c426-11ea-82b9-146dc02705f8.png)

Observed in: 2.4.5. Server version: 1.15 native, supporting ViaDev.

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there
