### ISSUE TITLE
[BUG] /is don't work

### ISSUE THREAD

**Issue by MrTalon63** [IridiumLLC/IridiumSkyblock#178]
**Describe the bug**
So when I join the server and try to type in any of /is command (only /is reload works) it just errors out with that https://hastebin.com/eqeninaqub.shell

**To Reproduce**
1. Start server
2. Join server
3. Try to type in any /is command

**Screenshots**
https://kek.analitycy.net/qfTMWpgV_
All of my plugins
Running latest paper 1.16.1
Iridium version: 2.4.6

**Comment by IridiumLLC** [comment]
Could you send me your islandmanager.json please :)

**Comment by MrTalon63** [comment]
It's empty

**Comment by IridiumLLC** [comment]
stop the server, delete islandmanager.json and start the server. should fix the issue
