### ISSUE TITLE
my island does not center [BUG]

### ISSUE THREAD

**Issue by MrSuricate2** [IridiumLLC/IridiumSkyblock#179]
**My island is not centered during its creation. I tried to modify the schematic.json to x=-25.0 and y=-25.0 but nothing changed. I also put the values x=-0.5 and y=0.5 but nothing changed either.  My schematic contains almost no air block. When I load the schematic and copy it, it centers me well in my chest.**

**To Reproduce**

**https://zupimages.net/viewer.php?id=20/29/ifcj.png**

**Comment by IridiumLLC** [comment]
> I tried to modify the schematic.json to x=-25.0 and y=-25.0 but nothing changed.

That has nothing todo with the island being centered. that modifies the default home position.

>  My schematic contains almost no air block

This might be an issue with worldedit, ill look into this
