### ISSUE TITLE
[BUG] Water Bucket error

### ISSUE THREAD

**Issue by Dqgs** [IridiumLLC/IridiumSkyblock#180]
**Describe the bug**
BIG ERROR in cosnsole

**To Reproduce**
1. 1.12.2 server
1. Create island
2. Place down Lava or water
3. go to console

**Screenshots**
https://cdn.discordapp.com/attachments/592092308514537510/733088329289040082/message.txt

**Comment by Ninjablader101** [comment]
bump

**Comment by IridiumLLC** [comment]
> bump

You know thats not how github works right? You cant bump bug reports. Ill look into this when I have time
