### ISSUE TITLE
[BUG] /is Command and /is delete

### ISSUE THREAD

**Issue by Derfavo** [IridiumLLC/IridiumSkyblock#181]
**Describe the bug**
The menu for /is is kinda empty
The command /is delete is not working at all

Server: 1.15.2 Paper
IridiumSkyBlock: 2.4.6

**To Reproduce**
First bug
Fresh install IridiumSkyblock
create an island with /is *island created*
Excecute /is again -> https://pastebin.com/Fzffc2HV

second bug
just type /is delete
click 'yes'
menu closes
error in console -> https://pastebin.com/W7bL5DX6

Edit: Booster & missions is also empty
Edit: /is delete cant handle the /spawn command from https://www.spigotmc.org/resources/premium-warps-portals-and-more-warp-teleport-system-1-8-1-16.66035/

**Screenshots**
![2020-07-17_19 07 47](https://user-images.githubusercontent.com/9658736/87812733-eb667f00-c860-11ea-8c35-00b47213d4fa.png)

**Comment by IridiumLLC** [comment]
Try updating your paperspigot version, I belive this was an issue on their side
