### ISSUE TITLE
[BUG][SUPPORT] Starting items island

### ISSUE THREAD

**Issue by Suulley** [IridiumLLC/IridiumSkyblock#182]
Hello dear creators

I want to change the items of the chest of the island. I was searching in config files, but I don't found nothing. At first I get the objects that you assigned by default, but after they don't even come out when I create the island. I reinstalled the plug-in and no items was in the chest. I want to put my custom items in the chest.Please help to change it. Sorry for my bad English, is not my language.

**Comment by IridiumLLC** [comment]
I dont do support on github, Join my support discord server for that
