### ISSUE TITLE
[BUG] Infinite Items from Shop

### ISSUE THREAD

**Issue by Philotastisches** [IridiumLLC/IridiumSkyblock#186]
Hey, you can get endless items from the shop when you run out of money. I don't think that's normal?

Video:
https://discordapp.com/channels/543944856498864169/671767766407315456/734073253643026493

**Comment by garsh1** [comment]
A user on my server has reported something similar.

**Comment by rrvk** [comment]
I saw also that, but i saw that the money on /is bank where used. if you run out of money that you had on your person.

**Comment by MertUnverdi** [comment]
This issue have has fixed at last update please use 2.5.2
if still not working please join us on discord:
https://discord.gg/PTpg4fD
