### ISSUE TITLE
Super flat terrain appears on the sky island

### ISSUE THREAD

**Issue by Cnzw** [IridiumLLC/IridiumSkyblock#189]
- paperspigot 1.12 
- plugin is lastest version

Super flat terrain appears on the sky island.

Super flat terrain surrounds the spawn point(first created skyblock island).

Cause other islands to have super flat terrain

[http://pan.cnzw.top:10602/#/s/VLcP](url)
This picture website in China,if you can't see it,I will try other website.
Thanks!

**Comment by IridiumLLC** [comment]
This is caused when the plugin disables, but people are still in the world, default generator takes over, nothing I can do
