### ISSUE TITLE
2 Shop questions

### ISSUE THREAD

**Issue by garsh1** [IridiumLLC/IridiumSkyblock#191]
My first questions is can I add custom items to the shop like a chunk hopper for example? My second question is can I make buttons in the shop that run a command? The second question is because I have a plugin that does allow me to add custom items so if this shop doesn't I can add the page there and make the command go to it.

**Comment by IridiumLLC** [comment]
Please only use the github issues for reporting bug reports, Questions and Suggestions should be said in the discord server: https://discord.gg/PTpg4fD
