### ISSUE TITLE
[SUGGESTION] add support with custom player skull texture and add custom model data in GUI items

### ISSUE THREAD

**Issue by ZacharyMSL** [IridiumLLC/IridiumSkyblock#194]
**CUSTOM PLAYER SKULL TEXTURE**
https://cdn.discordapp.com/attachments/592092308514537510/731548571815379074/unknown.png

now this plugin just support adding playerhead item with player name textures , but not custom texture heads just like headdatabase .

just like this base64 code

eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk1ZDM3OTkzZTU5NDA4MjY3ODQ3MmJmOWQ4NjgyMzQxM2MyNTBkNDMzMmEyYzdkOGM1MmRlNDk3NmIzNjIifX19

after decode

{"textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/c95d37993e594082678472bf9d86823413c250d4332a2c7d8c52de4976b362"}}}

you can find those custom texture player skull in https://minecraft-heads.com/custom-heads

And here is the tutorial it may help you to understand
https://bukkit.org/threads/create-your-own-custom-head-texture.424286/

**CUSTOM MODEL DATA**
in 1.14 version update , there has a item NBT called custom-model-data just updated . it can change item's model or texture with this nbt data . but this feature seems not on IridiumSkyblock plugin . So hope you may update it ~ thx

here is the tutorial for custom mode data 
https://datapackcenter.com/projects/custom-item-models-tutorial.69/

**reply to your question** about whats different between "custom texture player skulls" and "custom model data"

custom texture player skulls is only for change item: "minecraft:player_head" texture , the skull texture is base on "Base64 format" and Mojnag's player data to place on.

custom model data is talking about Change Item's Model via resourcepack , and you just need to add support with NBT tag "custom_model_data" only , for example i changed item: "minecraft:stick" custom_model_data to 1 , and it will automatic show other model if i installed a resourcepack

If you still dont understand about custom player skull texture or custom model data just ask me

**Comment by IridiumLLC** [comment]
Id prefer for all suggestions to be submitted via discord. Also I will add the custom player texture. but most likely wont add custom model data

**Comment by IridiumLLC** [comment]
p.s. the custom skull texture suggestion has already been submitted
