### ISSUE TITLE
[BUG] Players can access private islands and infinite void fall

### ISSUE THREAD

**Issue by evanthebearge** [IridiumLLC/IridiumSkyblock#195]
**Describe the bug**
When a player has fly activated in the corner of their island, they are able to escape the border by turning it off and then going under it to slip into a private island. They now also have the ability to infinity fall

**To Reproduce**
1. Turn off border in Player wanting to do glitch. The other player can have the border on or not, regardless.
2. Player creates a platform near the bottom of the island close to a neighboring's island platform
3. Player flies and uses flight inertia to fall on neighboring island platform which is lower than his
4. Player is now able to get into private/ other islands.

**Screenshots**
https://i.imgur.com/Doo5CNd.png
Player is in a different player's island which he does not own.

**Comment by Seliba** [comment]
There is currently no artificial protection against such a thing if you deactivate the Border.

What do you expect to happen when a player enters another private island?

**Comment by IridiumLLC** [comment]
> There is currently no artificial protection against such a thing if you deactivate the Border.
> 
> What do you expect to happen when a player enters another private island?

I suppose, we could use the Island#spawnPlayer to send then to the spawn, Ill add this later

**Comment by IridiumLLC** [comment]
Or send them back to their own island

**Comment by Seliba** [comment]
I don't think it would be smart to retrieve the current island in the PlayerMoveEvent listener just for that purpose

**Comment by IridiumLLC** [comment]
Ye, good point
