### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zimzaza4** [IridiumLLC/IridiumSkyblock#196]
Players can get items from the store through this vulnerability

Paper1.16

Please watch the video:
https://cdn.discordapp.com/attachments/729307699669368886/738387820510576740/QQ_0ff34cb4d165013fd905b07d8b6a41cc1596115700.mp4

**Comment by Seliba** [comment]
It seems your translator made a mistake. "Vulnerability" makes no sense in this context. Do the players have enough money to buy things, but aren't able to?

**Comment by IridiumLLC** [comment]
I think he means the fact that he took the iron axe from the shop inventory, if thats the case then its a ghost item and should dissapear if you relog, its just a client side bug
