### ISSUE TITLE
[BUG] getIslandViaLocation It's not covering the whole island.

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#197]
**Describe the bug**
Im make a plugin that on a mob spawn change the mob for a custom mob  in the islands, 
The higher the level of the Island, the greater the strength of the mob, improving its equipment,
add potions and stuff.
And when a mob spawn for check the island level i am using the getIslandViaLocation(Gets the location that the mob spawned) but in some places in the island spawn normal mobs, why in this location the island returns null.

My code: https://pastebin.com/7HVkRDVp (zumbiNivel1((Zombie) s.getEntity()); is the method that change the spawned mob)

**To Reproduce**
Go to the island board and spawn a mob.

**Screenshots**
My video: https://youtu.be/JjY6DA4GQ1w

**Comment by IridiumLLC** [comment]
I assume your using the latest skyblock version?

**Comment by PotenciaMax** [comment]
Yes. Before doing this I was already using the latest version of the plugin

**Comment by PotenciaMax** [comment]
My server server version is Paper 1.8.8
