### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by garsh1** [IridiumLLC/IridiumSkyblock#198]
**Describe the Suggestion**
Have the island value checked once and a while to refresh it. For example, blocks that are world edited are not counted towards the island value. If it checked let's say once ever 2-5 (Possible config value) minutes it would update eventually.

**Comment by IridiumLLC** [comment]
please keep all suggestions in the discord server

**Comment by IridiumLLC** [comment]
Also this is how it used to be, however it caused alot of lag, so now it updates one island every 2-5 minutes
