### ISSUE TITLE
[BUG] the island menu does not show up but it still works?

### ISSUE THREAD

**Issue by ItsZodiac** [IridiumLLC/IridiumSkyblock#199]
**Describe the bug**
basically i installed the plugin but when i tested it and did /is it brings up the island menu but it is only gray glass panes nothing else, the spots where there is supposed to be buttons do work but it does not show any icon

**To Reproduce**
1. type /is
2. click on any tile that is supposed to be a working button
3. it works
4. there is no icon for the button

**Screenshots**
![image](https://user-images.githubusercontent.com/69085873/89107064-55079100-d3fc-11ea-8d23-b38795b78355.png)

![image](https://user-images.githubusercontent.com/69085873/89107069-5df86280-d3fc-11ea-8f42-7e2cdbaee711.png)

**Comment by IridiumLLC** [comment]
Try updating your spigot version, this seems to fix it
