### ISSUE TITLE
[BUG] An issue with the default home position

### ISSUE THREAD

**Issue by kodaLee** [IridiumLLC/IridiumSkyblock#200]
**Describe the bug**
Basically whenever any of my users load up an island, it sets their home position to the side of the island instead of where I want them to spawn

I have tried modifying the schematics.json file and that doesn't seem to work as any of the x, y or z values in the json file don't change anything.

**Screenshots**
I have no idea what to show either than a want and current picture so here:
Want: https://i.imgur.com/4TVp7G5.png
Current: https://i.imgur.com/M5pLlhV.png

**Comment by kodaLee** [comment]
Yeah, its an issue with the latest build of your plugin as 2.4.6 or around that.

As 2.4.2 works with all my configs

**Comment by MertUnverdi** [comment]
added x,y,z offset options to schematics.json, your issues fixed with them?
if yes please close your issue <3
you can join our discord server:
discord.gg/PTpg4fD

**Comment by kodaLee** [comment]
2 months later, a person finally replys, when I'm not even doing minecraft shit anymore... ok.
