### ISSUE TITLE
dupe bug

### ISSUE THREAD

**Issue by VARboosted** [IridiumLLC/IridiumSkyblock#201]
https://cdn.discordapp.com/attachments/703323952260317255/740927122889244692/Screenshot_2020-08-06_at_14.38.23.png
known dupe bug important

second bug:

if you destroy your own nether portal inside the nether, and then you return to your island, and then you enter the portal again, you are linked to other island. 

sometimes this bug is not working i dont know how to do the bug.

after i flew a little bit in the nether island i've saw two nether islands

**Comment by Erorserv** [comment]
I'm getting the duplication glitch as well.

**Comment by LittlePotatoMC** [comment]
Yep same, also getting the duplication glitch.
