### ISSUE TITLE
WATCH THE TIMINGS REPORT [BUG]

### ISSUE THREAD

**Issue by SoyWama** [IridiumLLC/IridiumSkyblock#203]
**Describe the bug**
I did a time report on the server, and... Look at the huge amount of lag it gave:
https://timings.aikar.co/?id=eb1ea7f1916c4399998c25a2a115962c

In the console it does not generate errors or anything like that. Hope this helps fix it...

This server is running Paper version git-Paper-133 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT).
And and the IridiumSkyblock version is (IridiumSkyblock version 2.4.6)

**Comment by IridiumLLC** [comment]
Probabbly because you got a shitty server, try reducing the blocksPerTick in config.json

**Comment by SoyWama** [comment]
It may be, if ... How much do you recommend reducing it to? the server is 4gb and has no more than 20 plugins and is 1.16.1 ...
I would appreciate it if you would give me a recommendation since I don't know much about the plugin and I really don't know what that configuration is about. Thank you very much in advance!
________________________________

**Comment by SoyWama** [comment]
Another thing, sorry if I screw around a lot. What does that option do if the increase or decrease exactly? Thank you very much again in advance.
