### ISSUE TITLE
[BUG] Water bucket spamming in console

### ISSUE THREAD

**Issue by icansc187** [IridiumLLC/IridiumSkyblock#208]
**Describe the bug**
error in console using Iridium Skyblock 2.4.6

**To Reproduce**
1. /is create
2. place water bucket
3. bump error spamming in console

**Screenshots**
https://pastebin.com/uGzw5Am3

**Comment by Seliba** [comment]
Yep, it seems as a change made a few weeks ago by me uses a method that has another name in the 1.12 (PlayerBucketEvent#getClickedBlock() instead of PlayerBucketEvent#getBlock()).

Any ideas about how this should be solved @IridiumLLC?

**Comment by IridiumLLC** [comment]
Usually Id access that method using reflection, although this probabbly isnt the most efficient solution
