### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LucasHeh47** [IridiumLLC/IridiumSkyblock#209]
Whenever someone invites a player to an island or invites to coop the person receiving the invite gets kicked saying something like it cant parse component

**Comment by IridiumLLC** [comment]
Any errors in console?

**Comment by LucasHeh47** [comment]
no

**Comment by IridiumLLC** [comment]
If this is still an issue in the latest version, please could I get a screenshot/video @LucasHeh47
