### ISSUE TITLE
[BUG] 1.16.1 is top appreas 0 blocks after /is update all command

### ISSUE THREAD

**Issue by donvdp** [IridiumLLC/IridiumSkyblock#216]
when recalculation of all islands is done via the ingame command /is update all the /is top list apprears as all users having 0 blocks palced..

[see this image](https://imgur.com/undefined) before and after /is update all

Also
recalculation complete message appears twice, could indicate that this function is not working properly.

**To Reproduce**
1: check /is top and view a players island score
2: execute /is update all
after completion:
3: check /is top... all players appear to have 0 blocks placed.

This is fixed when a block is placed on the island again. placing 1 block on an island makes /is top update for that island.

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there

**Comment by donvdp** [comment]
beta didnt work, too many bugs, plugin is considderd broken and support takes too long, we have since switched to fabledskyblock, this works problemfree.
