### ISSUE TITLE
[SUGGESTION] island value not updated when worldediting blocks

### ISSUE THREAD

**Issue by donvdp** [IridiumLLC/IridiumSkyblock#217]
**Describe the Suggestion**
when i worldedit blocks on islands... those blocks do not count with the value of the island. Only manually placed blocks are added to the value of an island. 

I would like to have the ability to restore someone his/hers island by worldedition there island. rightnow when a player's island gets corrupt i need to manually edit there new island to its former glory by manually placing blocks.

**Comment by IridiumLLC** [comment]
please keep all suggestions in discord server
