### ISSUE TITLE
[SUGGESTION] /is setowner <name> command

### ISSUE THREAD

**Issue by donvdp** [IridiumLLC/IridiumSkyblock#218]
i've been having some issues with island ownership. sometimes when a few players are cooping or working together there ownership might get entangled.. the islandmanager sometimes gets corrupted.

When i tell players to create a new island it sometimes doesnt work, i would like to have a workarround for this issue by having a command that would let me (as admin) set ownership of an island to a certain player. For example... the island where i am on i would execute "/is setowner matze" --> this would transfer the ownership from the current owner of that island to the player called "matze"... also completly unsetting all previous ownerships of that player "matze" perhaps this could clear some island manager corrption.

**Comment by IridiumLLC** [comment]
try /is transfer, and keep all suggestions in discord please
