### ISSUE TITLE
[BUG] player cant do anything when tp to their island

### ISSUE THREAD

**Issue by chamo572** [IridiumLLC/IridiumSkyblock#220]
When a player visit another island and write /tp or /tpa to someone that already is in their island, the player cant do anything, (break, place blocks, open chests, etc)
The same thing happens if a player is in cooperative and is tp towards his partner

The /tp and /tpa is from essentialsX plugin

**To Reproduce**
1. Tp someone to your island
2. Visit another island
3. Write /tpa or /tp to teleport to the player thats is in your island

How to "fix", the player have to teleport to another world, in my case the spawn/lobby and teleport back to their island

**Comment by IridiumLLC** [comment]
Most likely is an issue with another plugin - Join support server for help
