### ISSUE TITLE
[BUG] wrong amount of blocks in /is top

### ISSUE THREAD

**Issue by chamo572** [IridiumLLC/IridiumSkyblock#221]
When write /is top you can view the amounts of mineral blocks thats a player have on their island, but sometimes it appears in negative numbers..
Example:
Iron blocks: -491

I dont know why is occurring that.. so idk to how to reproduce, (the blocks arent placed by world edit or a building plugin)

**To Reproduce**
1. Put mineral blocks on your island, thenthe break and place the blocks again
2. Write /is top, and hover the mouse on your island
(I dont know if it there the correctly steps to reproduce)

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there
