### ISSUE TITLE
[BUG] player respawn in another place that is not their island when die

### ISSUE THREAD

**Issue by chamo572** [IridiumLLC/IridiumSkyblock#222]
When a player dies in their island, he respawn in another place that not is his island (in my case, the normal nether) (not the nether island from iridium), I checked tue xonfigr and are all correctly, the spawn world is the spawn/lobby and not the nether... also I checked the multiverse plugin config..
The void-teleport option is in true..

**To Reproduce**
1. Stay in your island
2. Get killed by lava or mob

**Comment by IridiumLLC** [comment]
This isnt a bug, the plugin doesnt have a default spawn position. Download essentialsX and do /setspawn somewhere
