### ISSUE TITLE
[BUG] players after visit another island and come back to their island, spawn in nether portal

### ISSUE THREAD

**Issue by chamo572** [IridiumLLC/IridiumSkyblock#223]
The player write before /is sethome, but when write /is home to come back after visit other island, spawn in the top of their active nether portal

**To Reproduce**
1. Sethome with /is sethome
2. Visit another island
3. Come back to your island with /is home

(I dont know if this only happens to cooperative islands)

**Comment by Villmarksjenta** [comment]
I have this bug also. The bug also makes players spawn on top of the nether portal when they visit someone.

**Comment by MertUnverdi** [comment]
i think this problem is when home location is not safe
I've tried too many times but it works fine
if your issue was fixed please close it
also you can join our discord server:
https://discord.gg/PTpg4fD
