### ISSUE TITLE
[BUG] Unknown Crash

### ISSUE THREAD

**Issue by chamo572** [IridiumLLC/IridiumSkyblock#226]
First, the server doenst crash, it is the plugin, the server still active after the crash, but anyone can connect to them
Today it has been crashing to the point where you barely connect and crashing ... it is unplayable now .. I think it is an extreme rise in lag which causes the plugin to crash, the log is this (very long) 
https://pastebin.com/kh9EqX5R

**Comment by Erorserv** [comment]
What paper and Java versions are you running?
