### ISSUE TITLE
LimitedBlocks

### ISSUE THREAD

**Issue by MertUnverdi** [IridiumLLC/IridiumSkyblock#227]
This 1.8.x bukkit material name for piston
![20200814_194044](https://user-images.githubusercontent.com/69310169/90272802-979e8400-de66-11ea-9b03-cae493ff7dc6.jpg) 
And this Piston variable in Xmaterial 
![20200814_193902](https://user-images.githubusercontent.com/69310169/90273010-ecda9580-de66-11ea-97c6-a7886e665101.jpg)
That not same, and limitedBlocks not for piston on 1.8.x

And This 1.16.x bukkit's return material name for piston
![20200814_194126](https://user-images.githubusercontent.com/69310169/90273531-c832ed80-de67-11ea-9da4-f919e4c4fcfa.jpg)
That work for 1.9+

**Comment by IridiumLLC** [comment]
Have you re-tested this? Its probabbly fixed

**Comment by MertUnverdi** [comment]
yes i did still doesnt work (when put PISTON is still unlimited)

**Comment by BomBardyGamer** [comment]
In the new Iridium Skyblock 3.0, 1.8-1.12 support will be dropped. For this reason, I am going to close this report.
