### ISSUE TITLE
Island Value PlaceHolder Not Working

### ISSUE THREAD

**Issue by Reese14** [IridiumLLC/IridiumSkyblock#230]
When I add the placeholder '{hpe-iridiumskyblock_island_level-1-user}' or '{hpe-iridiumskyblock_island_level-1-value}' onto an hologram using HolographicDisplays with HolographicPlaceholders installed, the value is not displaying correctly. I have added the placeholder %iridiumskyblock_island_level% on the list of PlaceholderAPI's in the config.yml of HolographicPlaceholders, but it's still not working.

**Screenshots**
![2020-08-15_16 07 47](https://user-images.githubusercontent.com/68316028/90320719-96766100-df11-11ea-80a7-77daf122ea54.png)
![2020-08-15_16 08 01](https://user-images.githubusercontent.com/68316028/90320726-9bd3ab80-df11-11ea-95d4-56caf31dbf9f.png)

**Comment by Faun471** [comment]
You added the placeholder for the **island level** (%iridiumskyblock_island_level%) , instead of the **island value.** (%iridiumskyblock_island_value%).

**Comment by Reese14** [comment]
> You added the placeholder for the **island level** (%iridiumskyblock_island_level%) , instead of the **island value.** (%iridiumskyblock_island_value%).

I also tried that , does not work.

**Comment by MertUnverdi** [comment]
read it https://github.com/IridiumLLC/IridiumSkyblock/wiki/FAQ#holographic-displays
