### ISSUE TITLE
[BUG] server crashes due to duplicate IRON_BLOCK entry in islandmanager.json

### ISSUE THREAD

**Issue by donvdp** [IridiumLLC/IridiumSkyblock#231]
**Describe the bug**
Today the iridiumskyblock pluginbecame unusable. cause unknown, i assume a coding error.
on restarting the server, the startup messaged revealed that your plugin disabled itself due to an "duplicate key: IRON_BLOCK"
--- [see logfile](https://pastebin.pl/view/3ce77d00)

so i shut down the server again, drew a backup of the islandmanager.json file. and found out that there indeed is an island that has 2 entries for IRON_BLOCK ([see screenshot](https://imgur.com/lcwsM4n)). i have no idea how this is possible, i suppose there is an coding issue in the plugin that needs resolving.

can/will you resolve this? i'dd hate to run a plugin that can cause sudden server crashes....

**Comment by donvdp** [comment]
This morning i've concluded that this bug returns everytime the server is restarted.
at 04:20hours dutch time we automaticly restart the server, when unloading (shutting down) everything works just fine, but when the server is starting up the bug appears.

Seems like there is something wrong when your plugin unloads.

**Comment by IridiumLLC** [comment]
Could you send me your spigot jar along with your islandmanager.json

**Comment by donvdp** [comment]
we have stopped using iridiumskyblock due to too many buggs, maintaining our servers takes up allot of time for me, so i will not make any more time to help you guys develop a plugin. that time has passed, when i did make an effert your support was terrible.
