### ISSUE TITLE
[BUG]Missions not rewarding player with money

### ISSUE THREAD

**Issue by Dr0mus** [IridiumLLC/IridiumSkyblock#235]
**Describe the bug**
Whenever a player completes a mission they aren't rewarded the money afterwards nor the crystals for some reason, I have only edited the mission.yml
**To Reproduce**
1. Go to 'missions.yml'
2. 'edit the rewards'
3. save
??? I have no idea if that will work for other people but I think that is what happened to my server.
**Screenshots**

**Comment by IridiumLLC** [comment]
Check the /is bank only other reason I can think of is you messed the syntax up. Join the discord for support
