### ISSUE TITLE
[BUG] Failed to parse islandmanager.json - 1.16.2 Spigot

### ISSUE THREAD

**Issue by darkmage4** [IridiumLLC/IridiumSkyblock#236]
**Describe the bug**
Exactly what the title says.  
**To Reproduce**

22.08 10:00:17 [Server] Server thread/ERROR Failed to parse plugins/IridiumSkyblock/islandmanager.json: Aug 8, 2020, 5:37:27 AM
22.08 10:00:17 [Server] Server thread/INFO Disabling IridiumSkyblock v2.4.7
22.08 10:00:17 [Server] Server thread/INFO -------------------------------
22.08 10:00:17 [Server] Server thread/INFO IridiumSkyblock Disabled!
22.08 10:00:17 [Server] Server thread/INFO -------------------------------

FURTHER DOWN:
.08 10:00:17 [Server] Craft Scheduler Thread - 1/WARN Plugin IridiumSkyblock v2.4.7 generated an exception while executing task 10
22.08 10:00:17 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
22.08 10:00:17 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[spigot_1.16.2.jar:git-Spigot-379750e-9a9c223]
22.08 10:00:17 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:205) ~[spigot_1.16.2.jar:git-Spigot-379750e-9a9c223]
22.08 10:00:17 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:201) ~[spigot_1.16.2.jar:git-Spigot-379750e-9a9c223]
22.08 10:00:17 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.scheduleAsyncRepeatingTask(CraftScheduler.java:196) ~[spigot_1.16.2.jar:git-Spigot-379750e-9a9c223]
22.08 10:00:17 [Server] INFO at com.iridium.iridiumskyblock.gui.GUI.<init>(GUI.java:30) ~[?:?]
22.08 10:00:17 [Server] INFO at com.iridium.iridiumskyblock.gui.LanguagesGUI.<init>(LanguagesGUI.java:33) ~[?:?]
22.08 10:00:17 [Server] INFO at com.iridium.iridiumskyblock.gui.LanguagesGUI.<init>(LanguagesGUI.java:28) ~[?:?]
22.08 10:00:17 [Server] INFO at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$getLanguages$2(IridiumSkyblock.java:287) ~[?:?]

**Screenshots**

**Comment by SaengerItsWar** [comment]
try to delete the commas from the lastCreate and lastRegen line
example before as error: `"lastCreate": "Aug 8, 2020, 5:37:27 AM"`
after runs without error: `"lastCreate": "Aug 8 2020 5:37:27 AM"`

do the same for `"lastRegen": "Aug 8, 2020, 5:37:27 AM"`
                         `"lastRegen": "Aug 8 2020 5:37:27 AM"`
