### ISSUE TITLE
[BUG] Commands dont disable

### ISSUE THREAD

**Issue by Ateuss** [IridiumLLC/IridiumSkyblock#237]
**Describe the bug**
When I change the commands.json file from enabled: true to enabled: false the commands still work.

**To Reproduce**
here is example
  },
  "bankCommand": {
    "aliases": [
      "bank"
    ],
    "description": "Opens the bank GUI",
    "permission": "",
    "player": true,
    "enabled": false
  },

**Screenshots**

**Comment by IridiumLLC** [comment]
You need to restart the server for that to take effect

**Comment by MertUnverdi** [comment]
if your issue fixed please close.
if still not working, join our discord server <3
https://discord.gg/PTpg4fD
