### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AyItsJayy** [IridiumLLC/IridiumSkyblock#239]
When creating an island the console says "Schematic was made in a newer Minecraft version (2230 > -1). Data may be incompatible." and no items spawn in the chest

**To Reproduce**
1. Go to 'a server with the plugin on the latest version on 1.16.2'
2. Type '/is' or '/island' to create an island
3. See that the chest has no items

![image](https://user-images.githubusercontent.com/48923560/91359987-41610780-e7bb-11ea-8cf4-fcfd1837e34a.png)
![image](https://user-images.githubusercontent.com/48923560/91360017-4aea6f80-e7bb-11ea-8702-70dd98c98b83.png)
![image](https://user-images.githubusercontent.com/48923560/91360036-5473d780-e7bb-11ea-8493-5721cebf2504.png)

**Comment by IridiumLLC** [comment]
This is an issue with your worldedit version, simply update worldedit and it should work
