### ISSUE TITLE
[BUG] Island member invitation

### ISSUE THREAD

**Issue by FrankSchepers24** [IridiumLLC/IridiumSkyblock#240]
**Describe the bug**
When adding a member to your island, it sometimes says the member already has an island, when that's not the case. In order to fix that they need to create and island and delete it again before they can get invited.

**To Reproduce**
1. Start up 2 accounts
2. Let one account create an island and then delete it
3. Create an island with the other account and invite the other player.
4. It will show the message that the player already has an island.

**Screenshots**

**Comment by Seliba** [comment]
Unfortunately, I cannot reproduce this problem in the latest version
