### ISSUE TITLE
[SUGGESTION] Event API

### ISSUE THREAD

**Issue by ChiefMoneyBags** [IridiumLLC/IridiumSkyblock#243]
Hello, I am suggesting the implementation of 2 events.
- An Island value change event that fires upon the re-calculation of an island value or if value is otherwise manually added or removed for any reason.
- A mission progress change event that fires when a new mission tier is reached, when a mission is reset or the progress is in any way affected.

I am finding it rather difficult to hook into IridiumSkyblock at the moment without the presence of these events natively in the plugin.
Thank you for your time.

**Comment by IridiumLLC** [comment]
Hi, Id appreciate it if you could keep all suggestions in the discord server, also im really busy currently so I wont be able to add this for a while (if im honest probabbly atleast a month) so If your a java developer feel free to add it yourself and do a pull request

**Comment by ChiefMoneyBags** [comment]
Ok thank you for your reply
