### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rooster7679** [IridiumLLC/IridiumSkyblock#250]
**Describe the bug**
A clear and concise description of what the bug is. so people can place water and lava buckets on other peoples island without perms. is there a way to fix this?

**To Reproduce**

**Screenshots**

**Comment by MertUnverdi** [comment]
did you chech island permissions?

**Comment by rooster7679** [comment]
yea in game they are all turned off yet people can still place certain blocks like tnt and buckets of water and lava. Is there a command in the config to fix this?
