### ISSUE TITLE
[BUG] Island chest generates with no contents

### ISSUE THREAD

**Issue by LukeOnuke** [IridiumLLC/IridiumSkyblock#252]
**Description**
Bug that generates new islands **with empty chests**. 

So far ive found that it only occurs with world edit

**To Reproduce**
1. Download IridiumSkyblock `v2.4.8` (latest version at the time of making this bug report)
2. Install IridiumSkyblock as plugin
3. Install latest world edit (`7.2.0-beta04`)
4. Generate new island

**Post scriptum**
_I have no idea if its IridiumSkyblock's fault or WorldEdit's fault_

**Comment by IridiumLLC** [comment]
This can happen depending on what mc version you are on. It should be fixed if you install latest world edit version though.
If it doesnt, put whatever items you want in the chest, then select the island using worledit //wand (make the area as small as possible) then do //schem save island.schematic and put the file it saves into the schematics folder in IridiumSkyblock
