### ISSUE TITLE
[BUG] Slimefun compatibility issue

### ISSUE THREAD

**Issue by redstonerblast** [IridiumLLC/IridiumSkyblock#255]
**Describe the bug**
So I have a server I am setting up that is sky factory based, everything was working fine and I made my show case island with machines (Slimefun)... The problem started when I reset my island. First the holograms didn't disappear and second the machines were still "technically" there (I Used WorldEdit to move blocks to suspected machine locations and when I broke the block it dropped the "machine"). This made playing feel horrible as my friend couldn't place blocks randomly. This is not a slimefun error as this doesn't happen with other skyblock plugins.
**To Reproduce**
1. Place a machine (Slimefun) in your skyblock.
2. Place a machine that has a hologram, such as the Energy Regulator
3. Reset Island

**Screenshots**

**Comment by IridiumLLC** [comment]
You will need to contact the Slimefun developer and ask him to add support
