### ISSUE TITLE
Cant edit Inventory "Upgrades"

### ISSUE THREAD

**Issue by Juflos** [IridiumLLC/IridiumSkyblock#26]
Hey i cant edit the Inventory "Upgrades" in Inventorys.yml because there isnt something for the Upgrades Inv..... pls fix it

**Comment by adaliszk** [comment]
I'm a bit lost, you want to edit the Inventories or the Upgrades?

**Comment by Juflos** [comment]
The Inventroy from "Upgrades" 
All another inventories can edited but the Inv for "upgrades" not

**Comment by MineShard** [comment]
Still broken

**Comment by IridiumLLC** [comment]
you need to delete the Inventory.json and let it regenerate
