### ISSUE TITLE
[BUG] Infinite island creation

### ISSUE THREAD

**Issue by MertUnverdi** [IridiumLLC/IridiumSkyblock#264]
I think this issue is most important ever

place water to everywhere of island
![2020-09-26_23 13 12](https://user-images.githubusercontent.com/69310169/94349588-809aa680-004e-11eb-938f-f77f232e26cc.png)
don't forget the top of the tree
![2020-09-26_23 13 24](https://user-images.githubusercontent.com/69310169/94349600-a162fc00-004e-11eb-9ded-a5af1319e5b2.png)
and execute /is home or /is visit <yournick>
result: infinite island creation(infinity schematic pasting) and finally server will shutdown

Causing this problem when using Fawe or WorldEdit
but same for without Worldedit

**Comment by IridiumLLC** [comment]
can you send me your worldedit jar?

**Comment by MertUnverdi** [comment]
I tried it without WorldEdit is not about with Worldedit or fawe
