### ISSUE TITLE
Vault support

### ISSUE THREAD

**Issue by adaliszk** [IridiumLLC/IridiumSkyblock#27]
The idea to earn crystals and purchase Skyblock specific things is okay, but I wonder if it would be really hard to implement Vault API as an opt-in feature. With the support, servers with already established economies would able to integrate your game mode into their systems.

**Comment by GNUGradyn** [comment]
Vault support is absolutely essential in any plugin where buying or selling anything is involved

**Comment by IridiumLLC** [comment]
added
