### ISSUE TITLE
[BUG] can't eat most of the

### ISSUE THREAD

**Issue by rrvk** [IridiumLLC/IridiumSkyblock#284]
**Describe the bug**
When i am on my island i can't eat most of the time. The eating animation wil play but it will never stop (only occasionally it will work)

**To Reproduce**
1. Go to your island
2. Get hunger
3. Try to eat
4. If you can eat this time then go to Step 2. Until the eating animation just repeates and no food is added

**Other**
This is on version 2.5.0 I reverted back to 2.4.8 and then it works again

**Comment by Seliba** [comment]
Should be fixed in #277
