### ISSUE TITLE
[BUG] IS SHOP

### ISSUE THREAD

**Issue by Togalkan** [IridiumLLC/IridiumSkyblock#306]
Hello, I come back to report a second bug at the is shop level, it is impossible to resell several stacks, unfortunately it only works with 1 stack of item, thank you for your quick response!

cordially

**Comment by rrvk** [comment]
This has already been fixed but not ready uploaded to spigot
https://cdn.discordapp.com/attachments/592092308514537510/765225736138915870/IridiumSkyblock-2.5.1.jar

You can also join the discord for fast support ;)
