### ISSUE TITLE
[BUG] Chests don't have contents when using 1.13+ schematics

### ISSUE THREAD

**Issue by Vanityra** [IridiumLLC/IridiumSkyblock#31]
**Description**
When using a schematic created in 1.13 or higher, chests do not have their contents when creating an island.

**To Reproduce**
1. Build an island and create a schematic in 1.13 or higher with chests and their contents and insert that schematic in the schematic folder of Skyblock.
2. Reload using /is reload and create an island using that schematic
3. Check chests

**Comment by IridiumLLC** [comment]
Can you send me your schematic via discord?

**Comment by IridiumLLC** [comment]
fixed
