### ISSUE TITLE
[BUG] skyblock shop not shwoing up as a command and not working

### ISSUE THREAD

**Issue by Lavamate786** [IridiumLLC/IridiumSkyblock#312]
**Describe the bug**
So pretty much when i try to do /is shop. it shows up has a unknown command and i dwnloaded vault i am on 1.16.3 if that makes a diffrence and i chcked my console and there is nthing wrong and i am opped on my server.
**To Reproduce**

**Console Error**
If applicable, a pastebin link of any console errors

**Screenshots**

**Comment by IridiumLLC** [comment]
Join support server for support
