### ISSUE TITLE
[BUG] fromLegacy

### ISSUE THREAD

**Issue by javitype** [IridiumLLC/IridiumSkyblock#314]
public BlockData fromLegacy(Material material, byte data) {
        if (!legacy.containsKey(material.name() + data))
            legacy.put(material.name() + data, Bukkit.getUnsafe().fromLegacy(material, data));
        return legacy.get(material.name() + data);
    }

Proof: https://prnt.sc/v24bzg

HELP PLEASE how can I solve it?

**Comment by Seliba** [comment]
How is that related to IridiumSkyblock?

**Comment by IridiumLLC** [comment]
I think thats code from the Source

**Comment by IridiumLLC** [comment]
Eitherway, its not and issue with Iridium, probabbly importing wrong spigot api
