### ISSUE TITLE
[BUG]  Failed to parse plugins\IridiumSkyblock\islandmanager.json:

### ISSUE THREAD

**Issue by AabegR** [IridiumLLC/IridiumSkyblock#315]
Failed to parse plugins\IridiumSkyblock\islandmanager.json: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

Version 2.4.6 Tried 2.5.1 but lost all islands islandmanager.json is the Problem

I stopped playing and then I came back after 2 weeks to find out SkyBlock stopped working sometime before.

But if I start over v2.4.6 Completly clean files it works so would the file be dead or something?

**Comment by IridiumLLC** [comment]
Join support server for help, but it looks like somone tried to edit your islandmanager.json and corrupted it
