### ISSUE TITLE
[BUG] Any tree plant don't grow, leaves don't dissapear.

### ISSUE THREAD

**Issue by wink05** [IridiumLLC/IridiumSkyblock#316]
**Describe the bug**
I tried growing a tree but this just don't work, I tried using bonemeal and that's the only one method to grow any plant. Also leaves just don't dissapear, they stay and you have to break them by yourself. Only think that I can see growing is wheat and other like that.

**To Reproduce**
1. Plant a tree or any other plant
2. After bonemealing a tree and destroying wood leaves will not dissapear.

**Console Error**
Console does not give any error.

**Screenshots**
I don't think any is needed, everyone know how tree looks like.

**Comment by MertUnverdi** [comment]
that not a bug  you should set `disableLeafDecay` to false on config.json 
please read wiki firstly 👍
