### ISSUE TITLE
[SUGGESTION] isolate island mangemet

### ISSUE THREAD

**Issue by poohzaza166** [IridiumLLC/IridiumSkyblock#320]
so because the time and mob cap is limit and sync per island can we just put the island in new world or dimensions so the island size , time and mob cap can be remove and set per island cap and time useing 1.16 feature or use multiverse to do that

**Comment by IridiumLLC** [comment]
Hi, I prefer to keep this just for bug reports, if you would like to create a suggestion please do so on the discord server:

discord.gg/PTpg4fD
