### ISSUE TITLE
[BUG] Inventory not being cleared during a regen while clearInventory set to true

### ISSUE THREAD

**Issue by DoubleYouCash** [IridiumLLC/IridiumSkyblock#324]
**Describe the bug**
While the clearInventory config option is set to true, regenerating an island does not clear a user's inventory. 

**To Reproduce**
1. Set clearInventory option to "true" in the config
2. Reload Plugin/Restart Server (Neither fixed the issue)
3. Fill Inventory
4. Regen Island

**Comment by IridiumLLC** [comment]
Fixed, update will be out on Monday
