### ISSUE TITLE
[BUG]   "OffEnabled": false in border won't work

### ISSUE THREAD

**Issue by MrMathias154** [IridiumLLC/IridiumSkyblock#327]
**Describe the bug**
`When in files "plugins/IridiumSkyblock/border.json"`
with
`"OffEnabled": false`

He have possibility to select Off border in menu

**To Reproduce**
Go to the menu border color and click on the place of Off/White border

**Console Error**
No error

**Screenshots**
https://dai.ly/x7x1x73

**Comment by MertUnverdi** [comment]
did tried restart server??
also please tell me on discord SlashRemix#0001

**Comment by IridiumLLC** [comment]
Sorry, I closed this without a reason, you didnt save the file -_-
