### ISSUE TITLE
Plugin IridiumSkyblock v2.5.3 generated an exception while executing task 452

### ISSUE THREAD

**Issue by ducdzz61** [IridiumLLC/IridiumSkyblock#333]
1: https://hastebin.com/yajecevero.properties
2: https://hastebin.com/cumufeyavu.properties
pls fix :(

edit:
server ver: paperspigot 1.15.2
pl ver: v2.5.3

**Comment by Faun471** [comment]
Have you joined the discord server?

**Comment by MertUnverdi** [comment]
it can be about with your inventories.json
if you need help, join our discord server: discord.gg/PTpg4fD

**Comment by MertUnverdi** [comment]
i think this already fixed on our discord server
if fixed please close this issue

**Comment by ducdzz61** [comment]
I need an updated fix on spigot pls

**Comment by MertUnverdi** [comment]
Please tell us on our discord server 
discord.gg/PTpg4fD
