### ISSUE TITLE
/is bank money dupe bug

### ISSUE THREAD

**Issue by lmkr155** [IridiumLLC/IridiumSkyblock#334]
Player of my server told me he just fast clicking on bank withdraw, and that copy his money. He dupe money and withdraw to his /money. Version of IridiumSkyblock: 2.5.3

**Comment by MertUnverdi** [comment]
you're on vault 1.7.2?

**Comment by MertUnverdi** [comment]
Hey if issue already fixed please close issue
If not fixed yet, why dont answering me?

**Comment by MertUnverdi** [comment]
@IridiumLLC @dlsf
