### ISSUE TITLE
[BUG] [IridiumSkyblock] Plugin IridiumSkyblock v2.5.4 generated an exception while executing task 1788

### ISSUE THREAD

**Issue by DuAnti** [IridiumLLC/IridiumSkyblock#336]
After Updating from 2.5.3 to 2.5.4 i got this error/warn while someone tried /is

**To Reproduce**

**Console Error**
https://pastebin.com/4zcQZR1X

**Screenshots**

**Comment by MertUnverdi** [comment]
it's fixed on discord 👍
