### ISSUE TITLE
[BUG] Regen duplication glitch

### ISSUE THREAD

**Issue by DumbatorCZ** [IridiumLLC/IridiumSkyblock#34]
**Describe the bug**
/is regen will duplicate items in the chest and spits them out. Works on the island and out of it too.

**To Reproduce**
1. Have custom schematic island
2. /is regen
3. ???
4. Profit

**Screenshots**
[https://imgur.com/a/VTzyu3N](url)

**Comment by IridiumLLC** [comment]
Are you sure your on the latest version, once you do /is regen it will delete all entities in your island. Are there any errors in the console?
