### ISSUE TITLE
[BUG] Players able to build outside island border

### ISSUE THREAD

**Issue by CW-UK** [IridiumLLC/IridiumSkyblock#344]
**Describe the bug**
Players are able to build one block outside the island border.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an island
2. Turn borders off
3. Build out in any direction
4. Blocks will be prevented from placing, but only once they are more than one block outside the border.
5. Turn border back on to see rogue block outside the border.

**Console Error**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/6217127/98423300-2564c680-2086-11eb-9bd2-564215fcffbe.png)

**Comment by MertUnverdi** [comment]
This just for 1 blocks right?

**Comment by CW-UK** [comment]
> 
> 
> This just for 1 blocks right?

Yes, you can only get one outside the borders.. further placement is blocked.

**Comment by MertUnverdi** [comment]
okay i'll look it thanks for reporting it

**Comment by Mohamad82Bz** [comment]
I already sent this video in discord but i'll send it here too for reviewing (or maybe it can help you to find the issue faster)

This is the same bug, Island#getBylocation is returning null on the edge of one side
https://cdn.discordapp.com/attachments/592092308514537510/774728092585164820/irrdloc.mp4

**Comment by MertUnverdi** [comment]
Will be fixed on next update
