### ISSUE TITLE
Cannot prevent players from coming your island with fly.

### ISSUE THREAD

**Issue by Mohamad82Bz** [IridiumLLC/IridiumSkyblock#346]
Some ranks may have "Fly" permission in Skyblock, Players that have fly can turns their island's border off and fly around, Find other's islands, disturb or grief them with creepers (Agro the creepers to the chests). /is ban or /is expel and also /is private won't work because they are not coming as a visitor, they are in other's islands while the plugin is thinking they are in their "own" island.
Also, turning off "Border Off" is not a solution because there are many bypasses for Minecraft's border. (One example, Boat glitch)

The second issue that fly cause, Players get Adventure mode while visiting other's island, they can turn on their fly and go out, and they keep their Adventure mode until they execute `/is home` (There's no advantages in adventure mode, but still it can be an issue or low quality action)

Ways to stop this:
Way 1: Teleport players back to their island if they go 5 blocks far from the island's border.
Way 2: Warn them that their fly is going to off because they are going out of their island's border. (Logically, normal players cannot go out of the border because they can't place blocks out of the border)

Appreciate it. Thanks in Advance!

**Comment by MertUnverdi** [comment]
Will be fixed on next update
