### ISSUE TITLE
FREEZE-LAGS SERVER/PLUGIN [BUG]

### ISSUE THREAD

**Issue by Thin-Troll** [IridiumLLC/IridiumSkyblock#347]
**Describe the bug**
Eternal loading of chunks (islands), at each restart, every day, every minute, every millisecond, the islands are loaded and you always have to wait 15-20 minutes to be able to register a command.
this fucking still lasts. half a year already -- https://github.com/IridiumLLC/IridiumSkyblock/issues/150

**To Reproduce**
1. start a server with >500 islands
2. wait for a lagging server, because the plugin is stupidly unable to withstand a large number of islands
3. chunks are constantly loaded, after entering the server you need to wait 15 minutes for it to be possible to register a COMMAND

**Console Error**
https://pastebin.com/AydQuwmD

**Screenshots**
9000 chunks
![image](https://user-images.githubusercontent.com/61376903/98446795-0297e800-2142-11eb-8651-c03881feb143.png)

**Comment by Thin-Troll** [comment]
![Uploading image.png…]()

**Comment by Thin-Troll** [comment]
![image](https://user-images.githubusercontent.com/61376903/98447428-88b62d80-2146-11eb-80ce-f1542077648f.png)

**Comment by PeachesMLG** [comment]
Should be fixed
