### ISSUE TITLE
[BUG] Lag

### ISSUE THREAD

**Issue by Porkason** [IridiumLLC/IridiumSkyblock#358]
**Describe the bug**
Well insane and long lag spikes. 

**To Reproduce**
1. Go to 'Paper or Spigot 1.16.3'
Use the plugin. Experience insane server lags 
4. i donnow
**Console Error**
Well here is the spark report;
https://spark.lucko.me/#jdU7JptekL

**Screenshots**

**Comment by IridiumLLC** [comment]
https://timings.aikar.co/?id=fe0db250a3e24e15b75f65b19363d3db
