### ISSUE TITLE
[BUG] BlockListener Lag

### ISSUE THREAD

**Issue by TheThe123** [IridiumLLC/IridiumSkyblock#361]
Server tps is dropping because of **IridiumSkyblock::Task: com.iridium.iridiumskyblock.listeners.BlockBreakListener**

No console errors, just lagging my server

![blocklistener](https://user-images.githubusercontent.com/74457755/99148160-842dcf80-2686-11eb-8024-eec98f1ab02e.png)

**Comment by MertUnverdi** [comment]
duplicate with #358
