### ISSUE TITLE
Trees growth out side of the border! Player can't break those blocks.

### ISSUE THREAD

**Issue by Mohamad82Bz** [IridiumLLC/IridiumSkyblock#379]
Trees growth (with saplings) out side of the player's island boder, then player only can break that by upgrading his/her island size or the island will be cursed if was max size.

This screenshot explains everything:

![image](https://user-images.githubusercontent.com/65306187/99879199-6e894e80-2c20-11eb-81aa-eef25b1b2fce.png)

**Comment by MertUnverdi** [comment]
i think this can't unsolvable cause it same on the overworld's border 
if it doesn't causing any issue please close the issue report

**Comment by Mohamad82Bz** [comment]
Since player can't break anything out side of the border, it reduces quality imo.
This can be solved. Iridium can detect sapling growth and then check if it's near the island border, if the sapling was near the border, check out side of the border for blocks, if there were blocks, remove them. I guess it's possible to do.

**Comment by MertUnverdi** [comment]
ya im already think it so yes it possible but u did u think it for all islands?
can be grow a new tree per second it will can be some lag?

**Comment by Mohamad82Bz** [comment]
because of that i said check if the tree is near island border, a location check shouldn't use any performance at all.
And also it can run async cause it's not too important to check instantly fast,
