### ISSUE TITLE
[BUG] second player to create an island dies

### ISSUE THREAD

**Issue by NightRider0** [IridiumLLC/IridiumSkyblock#38]
**Describe the bug**
I have Iridiumskyblock on a 1.14 spigotmc server running on Ubuntu 18.04 LTS, the second person to generate an island and try to go to it while in survival mod dies from suffocating in a wall. plugin i is running default config, the "world" is set to flat with no creature spawns turned on. the server is running in a bungee network, with luckperm, essentialsx, advanced ban.

If needed i can grant you access to this this     
**To Reproduce**
1. Go to '/is'
2. Click on 'click on the bed in the GUI'
4. played died from suffocating in wall 

**ps**

I also cannot open chest

**Comment by IridiumLLC** [comment]
This sounds like an issue with the world border, teleport to the fist persons island and issue the command : /worldborder set 9999999

**Comment by NightRider0** [comment]
issued command from the first island and no change,

**Comment by IridiumLLC** [comment]
Contact me on discord: https://discord.gg/PTpg4fD and Ill help you out
