### ISSUE TITLE
[BUG] Chat

### ISSUE THREAD

**Issue by kichuMX** [IridiumLLC/IridiumSkyblock#387]
On the group-formats (EssentialsX) [ISLAND_VALUE] and [ISLAND_LEVEL] is the same on chat, I have valuePerLevel on 1000, and on scoreboard all is ok, but [ISLAND_LEVEL] doesn't show up in chat. I attach a picture how it look

https://i.imgur.com/K71TvnQ.png

**Comment by MertUnverdi** [comment]
Fixed with #430
