### ISSUE TITLE
[BUG] Nether Portal from Island to Real Nether

### ISSUE THREAD

**Issue by Acixsi** [IridiumLLC/IridiumSkyblock#388]
Whenever a player builds a netherportal on the very corner of their island and they enter the portal they will be teleported to the real nether instead of their netherisland. I discussed this bug before with SlashRemix, and he managed to fix it back then, I tested it afterwards and it was indeed fixed, but now another player from my server pointed out this bug, and when I tried it, I indeed got sent to the real nether instead of the island nether.

**Comment by AMDBartek** [comment]
I can confirm this issue, running 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2). This is very annoying, please fix.

**Comment by BomBardyGamer** [comment]
This issue has been resolved.
