### ISSUE TITLE
[BUG] Ender Pearls not working anymore

### ISSUE THREAD

**Issue by Acixsi** [IridiumLLC/IridiumSkyblock#389]
Ever since I updated Iridium Skyblock to version 2.5.6 or above, Ender Pearls wouldn't work anymore. When I try them I see the particles but won't get teleport. Maybe something changed when some Enderpearl issues were fixed, I don't have any other plugins installed, I did not have before the update.

**Comment by IridiumLLC** [comment]
Fixed
