### ISSUE TITLE
[BUG] Stacked Blocks Hologram also visible in Nether (blocks aren't)

### ISSUE THREAD

**Issue by Acixsi** [IridiumLLC/IridiumSkyblock#396]
I got a Bug-Report today on our server from a player, telling me that he could see the stacked blocks holograms in the Nether, although the stacked blocks aren't there.

![unknown](https://user-images.githubusercontent.com/30556494/100142129-aa781a00-2e93-11eb-8e15-dc9fdd38ac1b.png)

**Comment by IridiumLLC** [comment]
Oh, I completly overlooked this, thanks. Ill fix later

**Comment by IridiumLLC** [comment]
Fixed, will be released on monday
