### ISSUE TITLE
[BUG] "Duping bug" its more like exchanging low value blocks for high value ones

### ISSUE THREAD

**Issue by TheRealRude** [IridiumLLC/IridiumSkyblock#397]
If there is a fake hologram created with for example 100x iron blocks.
If you then place a diamond block under that block, you can mine 100x diamond block.
People turning 100x iron block in 100x netherite block here because netherite block is worth 10k is value on my serv :p

**Comment by TheRealRude** [comment]
I updated to recent update and it still happening

**Comment by IridiumLLC** [comment]
Should be fixed in 3.6.0
