### ISSUE TITLE
[BUG] Version for 2.2.4 There are two Bug

### ISSUE THREAD

**Issue by Laotouy** [IridiumLLC/IridiumSkyblock#40]
Please see the error below

https://paste.ubuntu.com/p/39PqSvq6Zh/

**Comment by IridiumLLC** [comment]
I am aware of the second issue, Join my discord and Ill help you fix the first one: https://discord.gg/PTpg4fD

**Comment by IridiumLLC** [comment]
Second issue has been fixed, join my discord and download the latest beta-version or wait until 2.2.5 releases tomorrow

**Comment by Laotouy** [comment]
Hello, author, because I am a Chinese developer, I cannot access the discord website in China, and I also hope to discuss it with you, but my English ability is poor, so I can only recover your message by mail, very Sorry! I will also clone your code from github to modify some of the text that cannot be modified in the configuration file. I like this plugin very much, and I also recommend this plugin with the developers around them, they all like it !!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "IridiumLLC"<notifications@github.com&gt;; 
发送时间: 2019年12月22日(星期天) 晚上11:01
收件人: "IridiumLLC/IridiumSkyblock"<IridiumSkyblock@noreply.github.com&gt;; 
抄送: "7"<18922569@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [IridiumLLC/IridiumSkyblock] [BUG] Version for 2.2.4 There are two Bug (#40)




Second issue has been fixed, join my discord and download the latest beta-version or wait until 2.2.5 releases tomorrow

**Comment by Laotouy** [comment]
Hello, I have joined your discord. How can I get in touch with you? My discord-ID is Laotou # 8198

**Comment by IridiumLLC** [comment]
Solved With user via discord
