### ISSUE TITLE
[SUGGESTION] Add A New PlaceHolder Without Format

### ISSUE THREAD

**Issue by rrodg12** [IridiumLLC/IridiumSkyblock#400]
**Describe the Suggestion**
I Would Love A Placeholder mainly for Island Crystals Like %iridiumskyblok_islandcrystals_unformated% So Instead of the Normal Placeholder show When Having over 1000 Island Crystals Is Currently Shows 1.1k Instead i would love anotherone that just says 1100 No Comma. Thanks!

**Comment by IridiumLLC** [comment]
Please keep all suggestions in the discord server :)
