### ISSUE TITLE
[BUG] Iand value missions broken

### ISSUE THREAD

**Issue by nicklanng** [IridiumLLC/IridiumSkyblock#401]
**Describe the bug**
~~Island value missions are not "fixed", but incredibly broken.~~
Island value reporting incorrectly after mission reset.

**To Reproduce**
Check your island value after mission reset.

**Console Error**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/2151074/100205149-a2a09000-2efc-11eb-829b-2fbe6d924c85.png)

**Comment by MertUnverdi** [comment]
maybe u broke some blocks and lost island level??

**Comment by nicklanng** [comment]
No block were broken, the user was fishing while the timer reset. When they went to check their fishing reward level they noticed this on the land value mission.

**Comment by PeachesMLG** [comment]
Ill look into this, but this is intended if they lose value since the mission starts

**Comment by BomBardyGamer** [comment]
This is intended behaviour, not a bug.
