### ISSUE TITLE
[BUG] Error while delete island

### ISSUE THREAD

**Issue by Querko242** [IridiumLLC/IridiumSkyblock#402]
Error log: https://hastebin.com/agoxavubon.sql

Server version:  git-Paper-288 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

List of plugins: AuthMe, AutoMessager, ClearLag, Essentials, EssentialsChat, EssentialsSpawn, IridiumSkyblock, LuckPerms, rhDrop, TabList, Vault, ViaVersion, WorldEdit, WorldGuar

**Comment by MertUnverdi** [comment]
Update to 2.5.9
