### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KhrysAK47** [IridiumLLC/IridiumSkyblock#404]
**Describe the bug**
If you are on your island, and a new player joins and generates a new island, your island (the one you are standing in) unloads and its like you are falling into the void, this is fixed by doing /island, but sometimes it's not fixed by doing that.

**To Reproduce**
1. Generate a island on latest version of Iridium
2. Stay on your island
3. Make a new player join and generate their island
4. Your island unloads (or it's chunks)

**Console Error**
No console error

**Screenshots**
Not applicable

**Comment by MertUnverdi** [comment]
WTF? please explain it..

**Comment by KhrysAK47** [comment]
> WTF? please explain it..

https://www.youtube.com/watch?v=2VFd50diW-A

**Comment by KhrysAK47** [comment]
That happened to all players that were on their islands when a new player joined and created their island.#

**Comment by 0VERR** [comment]
This also happens on my server when players enter the latest version of minecraft. (The server is on 1.8)
