### ISSUE TITLE
[BUG] Die for lava

### ISSUE THREAD

**Issue by reussy** [IridiumLLC/IridiumSkyblock#410]
**Describe the bug**
When you die from lava (I have only tasted lava) in the nether you appear on an island that is not yours 

**To Reproduce**
1. Die for lava in the nether...

**Vídeo**
https://youtu.be/Mn6aKxyK224

PS: This does not happen when dying falling into the void!

**Comment by MertUnverdi** [comment]
why blocks are outside of border ??
