### ISSUE TITLE
[BUG] Dead after falling to the void even with VoidTeleport

### ISSUE THREAD

**Issue by Vetom1k** [IridiumLLC/IridiumSkyblock#422]
Hey, the VoidTeleport is not working in offline mode 1.16.4, when i fall from my island i instantly die. Thanks. :)

**Comment by PeachesMLG** [comment]
any errors in console?

**Comment by Vetom1k** [comment]
I didn't see anything unusual, but gonna test it one more time.

**Comment by Vetom1k** [comment]
Literally nothing in console, only that i fell out of the world

**Comment by MertUnverdi** [comment]
Please contact to me on our Discord server
