### ISSUE TITLE
Freeze-SkyBlock[BUG]

### ISSUE THREAD

**Issue by Thin-Troll** [IridiumLLC/IridiumSkyblock#426]
**Describe the bug**
When a certain number of islands more than 400 is recruited, the server begins to count players for a long time.
You need to go in, wait 10-15 minutes and then the player will "load" and the commands will start working! UNTIL THIS TIME, COMMANDS CANNOT BE ENTERED.

**To Reproduce**
1. Install my islandmanager.json file
2. Wait until players ~ 50 people pass through the server
3. The islands will begin to load .. and the more players try to enter, the more it will be delayed for loading the players (islands) [The number of players is taken approximately, in general, my problem starts after 3-4 hours]
4. Commands stop being entered
After rebooting, the problem disappears, and it will return in ~ 50 players.

**Console Error**
No mistakes

**Video**
https://skr.sh/v5RoIp5M7zq?a
File islandmanager.json: https://yadi.sk/d/8oz6WDGoOpSl7Q

__________
Past threads #150 #347 
the problem with the chunks is gone, there are no errors.
but with non-working teams remained.
_______________
The problem has been going on for six months, but is it possible to ease my torment and make the command / is purge <day>
So that I can clean the old islands at least)

**Comment by Thin-Troll** [comment]
How the server behaves after a reboot. the first minute after switching on: https://skr.sh/v5RkIKTcutp?a
By the way .. chunks are constantly loaded at 700-1000

**Comment by PeachesMLG** [comment]
"The problem has been going on for six months, but is it possible to ease my torment and make the command / is purge
So that I can clean the old islands at least)"
This exists

**Comment by PeachesMLG** [comment]
also the new sql support should make stuff more efficient for large servers

**Comment by PeachesMLG** [comment]
Either way you dont need to remake a issue, the old one is still there

**Comment by PeachesMLG** [comment]
Not sure if the /is purge is on spigot yet tho, if its not you can download stuff from here: https://github.com/IridiumLLC/IridiumSkyblock/suites/1605595678/artifacts/29330971

**Comment by Thin-Troll** [comment]
> Not sure if the /is purge is on spigot yet tho, if its not you can download stuff from here: https://github.com/IridiumLLC/IridiumSkyblock/suites/1605595678/artifacts/29330971



> also the new sql support should make stuff more efficient for large servers

где мне найти поддержку Mysql? нигде об этом ни слова.
