### ISSUE TITLE
[BUG] Duplicate blocks with respawn anchor

### ISSUE THREAD

**Issue by omit01** [IridiumLLC/IridiumSkyblock#427]
Describe the bug
Duplicate blocks with respawn anchor

To Reproduce
How to replicate:
- Stack some Iron blocks
- Blow them up with a respawn anchor (maybe also end cristals). The plugin keeps the hologram with stacked blocks. 
- Place a netherite (or an other block with more value) block on the original place. 
- The blocks are now duped.

Normal behaviour:
Blown up blocks are removed or dropped.

https://youtu.be/waTcppQGR3k

**Comment by PeachesMLG** [comment]
Fixed
