### ISSUE TITLE
[BUG] Duplicate Blocks with fast clicking

### ISSUE THREAD

**Issue by omit01** [IridiumLLC/IridiumSkyblock#428]
**Describe the bug**
Duplicate Blocks with fast clicking

**To Reproduce**
- Make stacked air by clicking fast
- Place a valueble block (Or even a full shulkerbox)
- Break the blocks and enjoy your dublicate.

https://www.youtube.com/watch?v=s4W-81hskQI

**Comment by MertUnverdi** [comment]
i tried it faster than u but that didn't happened to me :(
