### ISSUE TITLE
[BUG] TERRIBLE LAGS

### ISSUE THREAD

**Issue by yooniks** [IridiumLLC/IridiumSkyblock#429]
The server is lagging horribly. It can't even keep up 30 players with no lags after no restart in a few hours.

![obraz](https://user-images.githubusercontent.com/30025818/101136482-af646880-360d-11eb-9ad0-2c49e3689d17.png)
You are literally creating 10 tasks and listeners PER ISLAND, it's so dumb and i can't believe you have done it. I guess you will not even fix it and i have to rewrite it on my own for hours. This plugin is terrible, a lot of bugs, copying blocks, lagging, not working features ;/

https://timings.aikar.co/?id=f59af904d96a4a4982068d0a538735dc
I have over 50 plugin and your plugin is the only one lagging, I'm really stupid that I have choosen your plugin, I thought it will really work and that my server will be the one with "new features" but the only thing i get is losing players because of poor written plugin.
https://i.imgur.com/zXItTim.png

**Comment by PeachesMLG** [comment]
Try updating to the latest version

**Comment by yooniks** [comment]
I'm using the latest version. I forked the resource to fix everything on my own because authors are too lazy to fix the bugs.

My version name is 2.5.6 but it contains 2.6.x patches (because i added it on my own). There are LOTS of bugs, I really didn't expect it to happen, idk why this resource has 5 stars on spigotmc, If i would have an account i would definitely leave a 1 star. It broke everything on my server, and I lost a lot of money, players and time to configure it, because it's not working properly.

Who had an idea to create 10 bukkit tasks per island? xD visitgui, biomegui, every gui has its own task PER ISLAND. 1000 islands = 10,000 tasks, great idea.

**Comment by tommasobenatti** [comment]
Wtf yooniks?

**Comment by MertUnverdi** [comment]
Please don't use the iridiumskyblock
just go back to Askyblock 👍

**Comment by PeachesMLG** [comment]
ok, well for obvious reasons I dont support forks, and your literally the only one who is having lag with gui's.

Also considering everything done with the gui schedulers is done async this is almost 100% something that you done

**Comment by MertUnverdi** [comment]
If u known the mean of this line, should known what u said is too silly
ye plugin will creating 10 tasks per island but those is not working for every miliseconds, that too easy task for CPU (than our brains 🧠)
`if (inventory.getViewers().isEmpty()) return;`

**Comment by yooniks** [comment]
> If u known the mean of this line, should known what u said is too silly
> ye plugin will creating 10 tasks per island but those is not working for every miliseconds, that too easy task for CPU (than our brains 🧠)
> `if (inventory.getViewers().isEmpty()) return;`
Of course I saw this line, which does not change the thing that there is still a logic behind scheduler#scheduleDelayed..., Also what about 10k listeners? All that shit is not optimized for bukkit and is made maybe for 5 players.

Another thing - players could break each others islands through" is visit" permissions of visitor changed every value to true for no reason, another thing - heads from visitgui crashed the server (of course you should know it will happen) - too many head texture requests wiłl crash the server. Another thing - schematics works like shit, i cant even set my own schematic because it is teleporting player anywhere but not on the center of island, I have tried everything. - It all happened with latest version. Another thing when I was using default version? Players copied thousands of blocks (diamond blocks etc) because of stupid bugs with pistons and hoppers and I had to reset whole server data so players lost everything. Of course the plugin is not prepared for big server.

**Comment by narumii** [comment]
It's like atomspigot that has kamikadze mode. (Async hits and movement system causes server crash XD)

**Comment by MertUnverdi** [comment]
if you're known much, Can be a good idea to make your own plugin?
Good luck to u 👍

**Comment by yooniks** [comment]
> It's like atomspigot that has kamikadze mode. (Async hits and movement system causes server crash XD)

It is fixed already, we just waited for new obfuscation





> if you're known much, Can be a good idea to make your own plugin?
> Good luck to u 👍

Great support, "go make your own plugin". Of course I would if i have time, whole plugin looks like it was made by kids that know 0 about clean code and we have almost 2021 year, i thought it looks better than askyblock from code side

**Comment by MertUnverdi** [comment]
Yes we are noob we can't fix we can't do 
Okay? 
Stupid kid go to use askyblock!!
Sick..

**Comment by PeachesMLG** [comment]
Dude ive already told you this is because you forked the plugin. You are literally the only one who has issues with gui's lagging the server.

**Comment by yooniks** [comment]
> Yes we are noob we can't fix we can't do
> Okay?
> Stupid kid go to use askyblock!!
> Sick..

Wait, lol?
Im on a need of support, im reporting the Bugs and you as support tell me to go using another plugin? Seems like you need to be reported on spigotmc, good luck with getting unbanned soon and thanks for the support. Also I will tell my friends about the situation so you will get more stars on spigotmc, sadly - the negative ones.
As you said - good luck.

**Comment by PeachesMLG** [comment]
> Seems like you need to be reported on spigotmc

Are you an idiot?
