### ISSUE TITLE
[BUG] Items being snapped at seemingly random locations!

### ISSUE THREAD

**Issue by sebastiantho** [IridiumLLC/IridiumSkyblock#431]
**Describe the bug**
At seemingly random places around people's islands, people are experiencing zones on their islands where items which are dropped from hand disappear immediately. 

**To Reproduce**
1. Go to 'Unclear yet'

**Console Error**
No errors in console when I drop. 

**Screenshots**
https://vimeo.com/487535942
Video of the occurrence.

**Comment by MertUnverdi** [comment]
That not related of iridium 👍

**Comment by sebastiantho** [comment]
> That not related of iridium 👍

Thanks for your response!
I'm a bit lost on what could be causing this if it isn't Iridium. 
What would be your best guess out of these plugins: ?
https://imgur.com/a/hUsyW5Z

**Comment by sebastiantho** [comment]
Curiously it fixed itself now. I fear it may reappear. I have no idea what is causing it.

**Comment by PeachesMLG** [comment]
ye im almost certain this isnt an issue with Iridium
