### ISSUE TITLE
[BUG] Item Remapping Handled Incorrectly

### ISSUE THREAD

**Issue by Foxxite** [IridiumLLC/IridiumSkyblock#44]
**Describe the bug**
This plugin tries to remap items to a legacy item, sometimes causing items to disappear when no legacy item is present,. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a schematic with items introduced in MC 1.13 or newer (sweet berries, coral, bamboo, honey, etc)
2. Set the schematic as one of the islands.
3. When the island is chosen the non legacy items will be removed.

**Proposed solution**
Either remove this feature or give us the option to disable it. Plugins like ViaVersion, Viabackwards and ProtocolSupport already handle this in a much more elegant way.

**Comment by IridiumLLC** [comment]
Added Support for world edit, as long as that is present this shouldn't be an issue
