### ISSUE TITLE
[BUG] /is admin with permissions won't open

### ISSUE THREAD

**Issue by BurkenDev** [IridiumLLC/IridiumSkyblock#444]
**Describe the bug**
When you do /is admin on a player island. For some reason then clicking on permissions in the GUI, the permissions GUI won't come up. It just closes the admin gui.

**To Reproduce**
1. Type /is admin
2. Click on Island permissions
3. GUI closes.

**Console Error**
Nothnig is reported on the console.

**Screenshots**
Can't paste screenshots here nor is it logical to take a screen shot of a closed gui.

**Comment by dlsf** [comment]
As this issue was created almost two months ago and we didn't receive any more similar issues, I guess it has been fixed now. Please re-open it if you still have problems.
