### ISSUE TITLE
[BUG] SQL error

### ISSUE THREAD

**Issue by reussy** [IridiumLLC/IridiumSkyblock#447]
**Describe the bug**
I do not have much information about the error, but when updating to 2.6.3,
 the plugin did not start.

_**No files were modified, all this happens with the new files that the plugin created**_

**To Reproduce**
1. Update to 2.6.3
2. Start server
3. See de console error

**Console Error**
https://paste.md-5.net/eyusiqihir.sql

**Comment by PeachesMLG** [comment]
Update: Only seems  to occur on 1.8

**Comment by PeachesMLG** [comment]
Fixed
