### ISSUE TITLE
Island top [BUG]

### ISSUE THREAD

**Issue by samuelovski1** [IridiumLLC/IridiumSkyblock#449]
**Describe the bug**
When I restart the server, the TOP placeholders and the RECALLCULATE COMMAND do only show/count players, that have joined after restart, It does not count any other players before (offline). In the screen I do use Placeholders for Island top name and level, both correctly setted up. I am certainly sure, that there are more than 3 players on my server with an own island. The 3 shown on the screen are the ones online after the restart.
Also, the /is top kinda glitches out

**To Reproduce**
1. Restart the server
2. Try /is recalculate
3. Look, that there is only certain amount of islands calculating (The amount is players, that joined after the restart)

**Console Error**
None

**Screenshots**
https://media.discordapp.net/attachments/592092308514537510/789050894078705694/unknown.png
https://media.discordapp.net/attachments/592092308514537510/789045703829356544/unknown.png

**File** - Peaches asked me to share it:
https://www.uschovna.cz/zasilka/FZ8GIPRX2R7997WY-92R/XZE69VLE2C

**Comment by PeachesMLG** [comment]
Fixed
