### ISSUE TITLE
[BUG] Item Data in schematics lost

### ISSUE THREAD

**Issue by Foxxite** [IridiumLLC/IridiumSkyblock#45]
**Describe the bug**
Item data in 1.13+ schematics are not being kept correctly. So do spawn eggs default back to pigs, player heads loose skin data, and items with a custom name, lore, or btn loose this data.

**To Reproduce**
1. Create a schematic with any of the previous described items
2. Set the schematic as one of the islands.
3. Observe the items having lost their custom data.

**Footnote**
Might be a bug with the worldedit implementation, pasting the schematics with worldedit doesn't reproduce this bug.

**Comment by IridiumLLC** [comment]
Added Support for world edit, as long as that is present this shouldn't be an issue
