### ISSUE TITLE
Im using JetsMinions but your plugin doesn't seem to let me place the minions in the skyblock world[BUG]

### ISSUE THREAD

**Issue by DeathReaper77** [IridiumLLC/IridiumSkyblock#451]
**Describe the bug**

**To Reproduce**
1. Go to your skyblock with all permisions '...'
2. Get a minion '....'
3. Try to place it down '....'

**Console Error**
Minion cannot be placed here

**Comment by RyVador** [comment]
That's not a bug, join the support discord https://discord.gg/FWrcVxQAzp
