### ISSUE TITLE
is TOP placeholders [BUG]

### ISSUE THREAD

**Issue by samuelovski1** [IridiumLLC/IridiumSkyblock#454]
**Describe the bug**
Not working as they should, they do only calculate/show islands of players, that join after server restart, ignoring the offline player ones making the TOP incorrect (Also /is top is having issues (did reported it on discord))

**To Reproduce**
1. Create a leaderboard with placeholders
2. Restart server
3. Join
4. And see, that all of the offline players are not displaying

**Console Error**
none

**Screenshots**
https://prnt.sc/w55525

**Comment by samuelovski1** [comment]
Also, version is the latest
https://prnt.sc/w555h2

**Comment by samuelovski1** [comment]
And no, Peaches did not fix it yesterday

**Comment by MertUnverdi** [comment]
it will be fixed on tmr please close it
