### ISSUE TITLE
How can I translate?

### ISSUE THREAD

**Issue by BJbit** [IridiumLLC/IridiumSkyblock#46]
I'd like to translate this plugins on my server. but All messages cannot be translated as message.json file.
what can I do?

**Comment by IridiumLLC** [comment]
Not sure why your posting this here, if you want support please use my discord: https://discord.gg/S9E368

You can translate the plugin by using the messages.json ect. Make sure that you are using correct json syntax. if your having errors try parsing it through a json validator https://jsonformatter.curiousconcept.com/
