### ISSUE TITLE
New Timer for weekly resett

### ISSUE THREAD

**Issue by cookyman83** [IridiumLLC/IridiumSkyblock#464]
Can you integrate a total hour display if you set Mission reset to weekly?
Currently it always shows it until the end of the day and that's wrong if you set it to weekly.

**Comment by MertUnverdi** [comment]
that timer is not for mission resets (is for midnights so bank interests etc.)
please join our discord and post it to suggestion channel here only bug reports
PEACHES IM STILL COULDN'T CLOSE ISSUESS!!!!
