### ISSUE TITLE
SQL console spam[BUG]

### ISSUE THREAD

**Issue by sebastiantho** [IridiumLLC/IridiumSkyblock#468]
**Describe the bug**
After reverting to a backup, I have been receiving this warning every time an interaction happens in an island. Like breaking a block, opening a chest etc. 

**To Reproduce**
1. Maybe revert to a backup? Unsure.

**Console Error**
https://pastebin.com/YkT0Ehcq

This isn't causing any bugs in-game, however the console gets clogged due to too many messages, so developing the server is hard. Is there at least a way to disable this console error?

Updating to 2.6.5 did not fix this.

**Comment by PeachesMLG** [comment]
> This isn't causing any bugs in-game
Doubt

By the looks of it your sql file is corrupted. Not quite sure what this  is. but it looks it is something you did

**Comment by sebastiantho** [comment]
I found the cause. It is cause by coreprotect, NOT iridium skyblock. It happened after reverting to a backup. Simply removing coreprotect and installing it again fixed the issue.
