### ISSUE TITLE
[BUG]Failed to get driver instance

### ISSUE THREAD

**Issue by TMGOtis** [IridiumLLC/IridiumSkyblock#472]
Skyblock is not loading on boot. I am getting a driver error when booting and when trying to run commands:"Failed to get driver instance for jdbcUrl=jdbc:sqlite:plugins/IridiumSkyblock/IridiumSkyblock.db"

I am running Spigot 1.8.8 and the newest version of Iridium Skyblock 2.6.5.

**Comment by PeachesMLG** [comment]
send console log
