### ISSUE TITLE
[BUG] Can still fly after fly booster expired

### ISSUE THREAD

**Issue by ReganWant** [IridiumLLC/IridiumSkyblock#477]
**Describe the bug**
Players can fly after the /is fly time is expired. This has only occurred since updating to latest version. 

**To Reproduce**
Use latest version of plugin. 
Purchase flight booster. 
wait for it to expire
You can still fly.  

**Console Error**
N/A

**Screenshots**
![671CA3E8-6E30-4917-909F-3B080038529F](https://user-images.githubusercontent.com/25869585/103446275-af3fa300-4c75-11eb-8af1-e201d15f518e.png)
![C219995A-09A2-4272-B1A4-37895FC36E25](https://user-images.githubusercontent.com/25869585/103446277-b1096680-4c75-11eb-9453-f85ee2a58cfa.png)

screenshots show timer ran out (as shown on featherboard) and the player is still flying- as seen in second screenshot!

happy new year, btw :)

**Comment by dlsf** [comment]
Can't confirm. This only happens when the player has the permission "IridiumSkyblock.Fly" or "iridiumskyblock.fly".
