### ISSUE TITLE
[BUG] Island visit buggy after island delete

### ISSUE THREAD

**Issue by eliasol** [IridiumLLC/IridiumSkyblock#478]
**Describe the bug**
I had 3 islands (my friends' ones and mine), after deleting an island, it does not desappear in the visit menu, it simply get replaced by mine, so I deleted the 3 islands we had and now I see my island three times, even if I do not have one! And if I click on it, the plugin throws a NullPointerException.

**To Reproduce**
1. Create some islands
2. Open the visit GUI
3. Delete the islands
4. Re-open the visit GUI

**Console Error**
https://pastebin.com/sUu2Y5gb

**Screenshots**
![problema skyblock](https://user-images.githubusercontent.com/50332957/103456572-aabbce80-4cf7-11eb-9634-29aa2d31d263.PNG)

**Comment by MertUnverdi** [comment]
fixed on 2.6.6

**Comment by CharlesMoss** [comment]
https://procrossbow.com/
https://baitcastingreelz.com/
