### ISSUE TITLE
[BUG] Buying stacks of non-stackable items

### ISSUE THREAD

**Issue by omit01** [IridiumLLC/IridiumSkyblock#486]
**The bug**
When buying non-stackable items in the shop by shift-clicking, you obtain a stack in your inventory

**To Reproduce**
0. Add a non-stackable item in your shop
1. Go to the shop
2. Click shift while buying the non-stackable item
3. The non-stackble is placed in a stack in your inventory.

**Possible solution**
Disable buying with shift for non-stackable items.

**Screenshots**
https://media.discordapp.net/attachments/760975961981321248/795979541666332692/unknown.png
https://media.discordapp.net/attachments/760975961981321248/795985313838137384/unknown.png

**Comment by MertUnverdi** [comment]
we couldn't filter the items so you should remove it on ur shop 
also we recommend using another shop plugin so this a skyblock plugin our shop can be a bit bad

**Comment by PeachesMLG** [comment]
Fixed
