### ISSUE TITLE
[BUG] Second owner is stuck as owner

### ISSUE THREAD

**Issue by GhotiMayo** [IridiumLLC/IridiumSkyblock#490]
**Describe the bug**
I've ran into an issue where if you have 2 members of an island (owner and 1 member), then promote the member all the way to owner along-side yourself, there becomes no way to demote that user back down without deleting the island

**To Reproduce**
1. Create an island
2. Invite a player to join your island 
3. Promote that player to co-owner, then to owner after that
4.  Issue reached

**Comment by MertUnverdi** [comment]
Fixed at 2.6.6
