### ISSUE TITLE
[BUG] Errors and corrupted database after update to 2.6.7

### ISSUE THREAD

**Issue by Shieldowskyy** [IridiumLLC/IridiumSkyblock#495]
After updating the plugin, errors pop up when typing commands. The update also damaged the database.

Server Version: git-Purpur-936
Plugin Version: 2.6.7

>....[04:19:03 INFO]: krzysiote issued server command: /is setwarp testowy
>....[04:19:03 WARN]: java.lang.NullPointerException
>....[04:19:03 WARN]: at com.iridium.iridiumskyblock.Island.addWarp(Island.java:500)
>....[04:19:03 WARN]: at com.iridium.iridiumskyblock.commands.SetWarpCommand.execute(SetWarpCommand.java:27)
>....[04:19:03 WARN]: at com.iridium.iridiumskyblock.commands.CommandManager.onCommand(CommandManager.java:77)
>....[04:19:03 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>....[04:19:03 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
>....[04:19:03 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2074)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1877)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1830)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1202)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1195)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1171)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1015)
>....[04:19:03 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
>....[04:19:03 WARN]: at java.base/java.lang.Thread.run(Unknown Source)

**Comment by PeachesMLG** [comment]
Fixed, probabbly
