### ISSUE TITLE
[BUG] Other players can place lava and water

### ISSUE THREAD

**Issue by hufskhj1** [IridiumLLC/IridiumSkyblock#497]
players that do not have permission can install water and lava on other people's islands.

**Comment by BomBardyGamer** [comment]
Can you give me some details on your server version, plugin version, and where abouts players can place water/lava please?
Example:
- Server Version: 1.12.2
- Plugin Version: 2.6.7
- Players can place water/lava on other players' islands without permission.

**Comment by hufskhj1** [comment]
> Can you give me some details on your server version, plugin version, and where abouts players can place water/lava please?
> Example:
> 
> * Server Version: 1.12.2
> * Plugin Version: 2.6.7
> * Players can place water/lava on other players' islands without permission.

Server Version: 1.16.4 paper
Plugin Version: 2.6.6

It is not always a bug. Sometimes a player without Permission uses lava/water to terrorize other islands, but I don't know the exact conditions. I think the island's protection is somehow being breached.

**Comment by PeachesMLG** [comment]
https://youtu.be/6je-B-nkBR8

**Comment by anticuatro** [comment]
> https://youtu.be/6je-B-nkBR8

up
**will you do it?**

My data:
PaperSpigot 1.12.2
tested on Spigot 1.12.2 the problem remains

version plugin: latest 2.6.7
the bug also works in the past

**Comment by anticuatro** [comment]
> https://youtu.be/6je-B-nkBR8

up
26 d open!! 
**will you do it?**

My data:
PaperSpigot 1.12.2
tested on Spigot 1.12.2 the problem remains

version plugin: latest 2.6.7
the bug also works in the past

**Comment by dlsf** [comment]
This is a Minecraft / Spigot / Paper bug. It only happens when you place water or lava in a way that there is no gray box around the block indicating that you are looking at it. For some reason, this is possible.

**Comment by dlsf** [comment]
After some more testing, I found out that this is a Spigot bug. Placing fluids outside of the placing distance is not possible in my Vanilla Minecraft world.

**Comment by dlsf** [comment]
Update: I reported the bug to Spigot, https://hub.spigotmc.org/jira/browse/SPIGOT-6351
