### ISSUE TITLE
[BUG] Fishing rod on other island

### ISSUE THREAD

**Issue by hufskhj1** [IridiumLLC/IridiumSkyblock#502]
Other players can fish on other people's islands. This bug can be used to pull and terrorize animals on other people's islands.

**Comment by CharlesMoss** [comment]
https://baitcastingreelz.com/

**Comment by BomBardyGamer** [comment]
![](https://cdn.prevarinite.com/jacksucksatlife-stick-to-the-format.gif)

**Comment by dlsf** [comment]
I feel like this is rather an issue with your fishing plugin. With Vanilla fishing mechanics, this can't happen.

**Comment by hufskhj1** [comment]
no i don't have any fishing plugin. People are suffering from a slight drag when they catch animals with a fishing rod.

**Comment by hufskhj1** [comment]
> I feel like this is rather an issue with your fishing plugin. With Vanilla fishing mechanics, this can't happen.
no i don't have any fishing plugin. People are suffering from a slight drag when they catch animals with a fishing rod.

**Comment by hufskhj1** [comment]
no i don't have any fishing plugin. People are suffering from a slight drag when they catch animals with a fishing rod.
