### ISSUE TITLE
[BUG] Island block limit bypass

### ISSUE THREAD

**Issue by tncc2k** [IridiumLLC/IridiumSkyblock#508]
Plugin version: Iridium Skyblock 2.6.7
Spigot buildtool: 1.10.2

I tried to set the hopper and it went over the limit

https://user-images.githubusercontent.com/77291313/104215234-1413ae00-546b-11eb-8b07-de1d05da1043.mp4

https://user-images.githubusercontent.com/77291313/104215292-25f55100-546b-11eb-9902-1b91a842dfb5.mp4

**Comment by tncc2k** [comment]
it is more likely to happen to a hopper than to a block

**Comment by BomBardyGamer** [comment]
![](https://cdn.prevarinite.com/jacksucksatlife-stick-to-the-format.gif)

**Comment by dlsf** [comment]
I can't replicate this on the latest version of IridiumSkyblock with Spigot 1.16.5. This might be an issue with another plugin or your server software.
