### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiscool123** [IridiumLLC/IridiumSkyblock#51]
**Describe the bug**
After I created an island, I log out. Then, I log in on the day after and it has recreated my island somewhere else (I could still see my old island far away).

**Screenshots**
![2020-02-01_10 44 18](https://user-images.githubusercontent.com/46547855/73594817-d9c23280-44df-11ea-869a-a75445c681b4.png)

**Comment by IridiumLLC** [comment]
This issue was fixed a while ago. Please the the latest #beta-versions jars in my discord
