### ISSUE TITLE
[BUG] Placeholder for exp boosters

### ISSUE THREAD

**Issue by MCAzertox** [IridiumLLC/IridiumSkyblock#515]
I'm on 2.6.7 version of IridiumSkyblock and one placeholder doesn't work anymore

**Screenshots**
![image](https://user-images.githubusercontent.com/55854952/104463395-0288ee00-55b2-11eb-8957-42c4a344b5f0.png)

**Comment by PeachesMLG** [comment]
my bad, should be experience instead of exp now. I recoded how the boosters work.

**Comment by MCAzertox** [comment]
When it will be fixed ?
