### ISSUE TITLE
[BUG]Can`t withdraw money from bank

### ISSUE THREAD

**Issue by Alice-space** [IridiumLLC/IridiumSkyblock#52]
**Describe the bug**
Can`t withdraw money from bank,just left-click doesn`t work.Exp and crystals work well.Only money can`t be withdrawed.
(English is not my native language.)

**To Reproduce**
1./is shop
2.left-click bank/money

**Screenshots**
![image](https://user-images.githubusercontent.com/47878052/73628104-3cefc880-468a-11ea-9189-566085988991.png)

**Comment by Alice-space** [comment]
Environment:
Ubuntu 18.04LTS 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
using paper-87 server

**Comment by Alice-space** [comment]
version 1.15.2

**Comment by IridiumLLC** [comment]
Do you have vault installed?

**Comment by Alice-space** [comment]
I didn`t.Sorry.
But I found nothig about this on wiki.Add it please.

**Comment by Alice-space** [comment]
I fixed wiki.
A good plugin.Thanks.
