### ISSUE TITLE
[BUG] Island size

### ISSUE THREAD

**Issue by cookyman83** [IridiumLLC/IridiumSkyblock#520]
Beautiful good day,
we found another bug.
This affects the size of the island or the upgrading of the size of the island.

In the config I have distance: 151 it also recognizes this correctly,
but in the upgrade file I have the following:

`  "islandSizeUpgrade": {
    "name": "size",
    "enabled": true,
    "upgrades": {
      "1": {
        "crystalsCost": 0,
        "vaultCost": 0,
        "size": 20
      },
      "2": {
        "crystalsCost": 1,
        "vaultCost": 10000,
        "size": 50
      },
      "3": {
        "crystalsCost": 2,
        "vaultCost": 15000,
        "size": 75
      },
      "4": {
        "crystalsCost": 3,
        "vaultCost": 30000,
        "size": 100
      },
      "5": {
        "crystalsCost": 3,
        "vaultCost": 50000,
        "size": 150
      }
    },
    "item": {
      "material": "GRASS_BLOCK",
      "amount": 1,
      "title": "&b&lIsland Size",
      "lore": [
        "&b&lInformation:",
        "&b&l * &7Current Level: &b{sizelevel}",
        "&b&l * &7Current Size: &b{sizeblocks}x{sizeblocks} Blocks",
        "&b&l * &7Upgrade Cost: &b{sizecrystalscost} Crystals and ${sizevaultcost}",
        "&b&lLevels:",
        "&b&l * &7Level 1: &b20x20 Blocks",
        "&b&l * &7Level 2: &b50x50 Blocks",
        "&b&l * &7Level 3: &b75x75 Blocks",
        "&b&l * &7Level 4: &b100x100 Blocks",
        "&b&l * &7Level 5: &b150x150 Blocks",
        "",
        "&b&l[!] &bLeft Click to Purchase this Upgrade"
      ],
      "slot": 10
    }
  },`

Now it is so that I have level 3 that means 75 blocks,
but I can continue to build until this max distance has been reached.
Another player who has a level 5 upgrade so 150 blocks and can build up to half on my island.
Don't have to be
if there are 150 blocks there, you can build 75 blocks to the north and 75 blocks to the south?

Addendum:
If you build in a direction where there is no other island,
because this island size restriction applies.
If you build in one direction where there is an island, this restriction does not apply until the max distance blocks the further building.

**Comment by BomBardyGamer** [comment]
![](https://cdn.prevarinite.com/jacksucksatlife-stick-to-the-format.gif)

**Comment by MertUnverdi** [comment]
the distances only appears to new islands

**Comment by dlsf** [comment]
Like @MertUnverdi wrote, this is most likely a configuration issue. The island size upgrade is in both directions. 

Please reach out to us via Discord if you still experience problems regarding the island size or re-open this issue.
