### ISSUE TITLE
Non-Member players can destroy itemframes with projectiles [BUG]

### ISSUE THREAD

**Issue by FADEOffical** [IridiumLLC/IridiumSkyblock#524]
**Describe the bug**
A player who is not a member of the island can destroy ones itemframes.

**To Reproduce**
1. Go to an island of which you are not a member
2. Get some snowballs for example (any similar thing will do)
3. Throw the snowball at the itemframe
4. See error (I guess)

**Console Error**
N/A

**Screenshots**
N/A

**Comment by PeachesMLG** [comment]
99% sure this was fixed

**Comment by PeachesMLG** [comment]
When 3.0.0 gets released reopen this if its not fixed
