### ISSUE TITLE
[BUG] Server Crash [NEW]

### ISSUE THREAD

**Issue by ErenAslaNN** [IridiumLLC/IridiumSkyblock#525]
Describe the bug
Iridiumskyblock is spamming the console with SQL related errors.

Server version: Taco 1.8.8
IridiumSkyblock version: 2.6.7

Console Error
https://paste.ubuntu.com/p/hYPHFPHKKc/

**Comment by ErenAslaNN** [comment]
New error: https://paste.ubuntu.com/p/qJ6f8xbdYS/

**Comment by Rhonim** [comment]
You're having database issues. Personally would recommend using MySQL/MariaDB instead of SQLite. The DB file being "locked" generally indicates its being used by another process. As for the new error, it looks like it can't connect to the database. Both generally are issues on your side.

**Comment by dlsf** [comment]
As mentioned by @Rhonim, switching to MySQL will fix this issue. Additionally, this kind of problem will be fixed in the next release, so I'll close this issue.
