### ISSUE TITLE
[BUG] IslandDemoteEvent inverted

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#528]
**Describe the bug**
The event.getRole() is inverted.
Example: when a player is demoted from member to recruit  the getRole() returns Role.Co-owner

**To Reproduce**

**Console Error**
If applicable, a pastebin link of any console errors

**Screenshots**

**Comment by BomBardyGamer** [comment]
https://tenor.com/view/jack-sucks-at-life-stick-to-the-format-gif-11209253

**Comment by BomBardyGamer** [comment]
![](https://cdn.prevarinite.com/jacksucksatlife-stick-to-the-format.gif)

**Comment by BomBardyGamer** [comment]
Can you please fill in the format properly?

**Comment by PeachesMLG** [comment]
![](https://cdn.prevarinite.com/jacksucksatlife-stick-to-the-format.gif)

**Comment by PeachesMLG** [comment]
But legit, steps to reproduce this would be really helpful because im an idiot

**Comment by PotenciaMax** [comment]
Reproduce the bug:
Step 1 register this event in a test plugin:

@EventHandler
public void test(IslandDemoteEvent e) {
   Bukkit.broadcastMessage(e.getRole().toString);
}

Step 2 create a Island whit 2 members
Step 3 demote a member (this will broadcast the 
the role that the demoted member will stay)

Bug description:
When for example a user is demoted from CO-OWNER to MEMBER the event above 
instead broadcast "Member" broadcast "Owner".

The bug is in the MembersGUI when call the IslandDemoteEvent
![Bug](https://user-images.githubusercontent.com/66755751/105203560-0670bf00-5b22-11eb-94c5-d45a5e54a1cd.PNG)


I already solved the bug for me, to solve, just change the Role.getViaRank(u.getRole(). Rank + 1) to Role.getViaRank(u.getRole().Rank - 1)
