### ISSUE TITLE
Use try w/ resource for DB

### ISSUE THREAD

**Issue by Rhonim** [IridiumLLC/IridiumSkyblock#529]
When doing database connections, statements, and result sets, you may want to make use of the try with resource functionality.

Generally looks something like the following:
`
try (Connection conn = dbmanager.getConnection(); PreparedStatement stmt = conn.prepareStatement("...")){
            stmt.setInt(1, 1337);
            try (ResultSet set = stmt.executeQuery()) {
                //Handle things here
            }
        }
`
This will auto close everything needed, even when it errors out. The current solution does not return connections back to the pool when it errors, nor does it close result sets.

**Comment by BomBardyGamer** [comment]
If you think this is a good idea, you could always make the changes yourself and submit a PR 🙂

**Comment by BomBardyGamer** [comment]
Also, the database system is currently in the process of being rewritten to use an ORM library called ORMLite to allow for better compatibility across database management systems.

**Comment by Rhonim** [comment]
I'll submit a PR for it later today.

When re-doing the database system you may want to look into normalization, and not using JSON for everything. If you're dealing with DB slow downs, that's likely why. Though, with using an ORM you may not have to worry about it.

**Comment by Rhonim** [comment]
Upon doing those changes I noticed that when getUser() is called, it has the potential (and often is) to be called on the main thread. Would be something you want to avoid in the future, as it slows down the whole server if a connection is taking longer to complete.
