### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by McHauge** [IridiumLLC/IridiumSkyblock#53]
**Describe the bug**
can't buy or sell Lapis lazuli and blue dye in shops.

**To Reproduce**
1. mc 1.15 or 1.14
2. buy/sell lapis lazuli or blue dye from shop
3. cant sell mined lapis and cant buy blue dye

**Fix**
After MC 1.14+ they introduced blue dye, and this should be updated in the "Multiversion Materials" list to match the new names.

lapiz lazuli -> "LAPIS_LAZULI"
blue dye    -> "BLUE_DYE"

and not some version of an inksack

**Comment by IridiumLLC** [comment]
This issue was fixed a while ago. Please the the latest #beta-versions jars in my discord

**Comment by McHauge** [comment]
might have been fixed, but it's not updated on the wiki then
- will go grab the beta now
