### ISSUE TITLE
[BUG] I updated the plugin and now is nothing loading

### ISSUE THREAD

**Issue by RicardormDev** [IridiumLLC/IridiumSkyblock#531]
**Describe the bug**
I don't know what is going on, but I updated to the last version and now nothing is loading. 

**To Reproduce**
Update the plugin to the last version on 1.16.5

**Console Error**
https://gist.github.com/RicardormDev/d1bb70104f6aa9c29ededdba090c21e2

**Comment by dlsf** [comment]
Please join our support Discord for such questions. If I'm not mistaken, you should update to version 2.6.1 before using 2.6.7.
