### ISSUE TITLE
[BUG] Formatted Level to Island Default

### ISSUE THREAD

**Issue by root2512** [IridiumLLC/IridiumSkyblock#534]
**Island level placeholders formatted**
There are already settings in config that we can turn these settings on or off. But this still does not go away after turning this setting off.

**Solution**
- Remove formatted level to island defaults.
https://github.com/IridiumLLC/IridiumSkyblock/commit/31734be526c9e546fe6cd18c36f26f8b141d6421

**Screenshots**
https://hizliresim.com/1sr06k

**Comment by MertUnverdi** [comment]
Bahsettiğiniz PR'm de sadece matematik işlemi yerine ada defaultlarına eklenmiş halini kullandım.
Kısacası hata olarak gördüğünüz  şeyin kaynağı orası değil

**Comment by root2512** [comment]
O eklediğiniz yamadan itibaren böyle bir sorun oluştu. Onun öncesinde normal çalışıyordu deneyin isterseniz.

**Comment by MertUnverdi** [comment]
Sorunun ne olduğunu rica edebilirmiyim? Alıntıdan bir şey anlayamıyoruz.
Türkçe veyahut Ingilizce farketmez

**Comment by root2512** [comment]
Sorun attığım ss'deki ada seviyesinin 1,071 olması gerekirken yanında .15 gibi bir şey ekleniyor. Config dosyasından bu ayarı kapatmama rağmen hala bu çıkıyor. O yamadan önce denediğimde böyle bir şey yok o eklediğiniz yama ve ondan sonraki yamalarda bu sorun var.

**Comment by MertUnverdi** [comment]
Tekrar söyleyeyim o bahsettiğiniz PR de sadece heryerde mat işlemi yapılmasını engelleyip adanın kendi içerisinde method çıkarmasını sağlamak için yapıldı.
Tekrardan bi inceleyip discord üzerinden bilgilendireceğim konuyu kapatmak zorundayım.

**Comment by MertUnverdi** [comment]
Evet floor eklememişim bunu düzeltiyorum bildiriniz için teşekkürler
