### ISSUE TITLE
[BUG] - island reset after destroy 1st layer of the grass

### ISSUE THREAD

**Issue by minecraft7net** [IridiumLLC/IridiumSkyblock#54]
**Describe the bug**

**To Reproduce**
remove 1st layer of the grass on the new island will reset to the new one island 

**Screenshots**

latest iridium skyblock
latest spigot or paper 1.15.2

**Comment by minecraft7net** [comment]
after destroy 1st layer 

/spawn
/is home

island is clear and new

**Comment by IridiumLLC** [comment]
Does this still occur on the latest version?

**Comment by 3DDario** [comment]
> Does this still occur on the latest version?

Yes, version 2.2.9 still has this problem.

Log (`/is home`): https://pastebin.com/raw/sssDjcfb
