### ISSUE TITLE
[BUG] Players can't break blocks at first time join

### ISSUE THREAD

**Issue by Stoiky20** [IridiumLLC/IridiumSkyblock#546]
hello, I have a problem with iridiumskyblock which is happening just the first time the user join
so they can break blocks, everything works
but they do not see the breaked blocks in their inventories
until they click on their inventory
Im running my server on 1.16.5 paperspigot

this is happening because of this line
"createIslandOnJoin": false,
when I have it on true
everytime a new user joins
they can break blocks but it will just not work to see them in their inventories
it is like a visual bug

**Comment by dlsf** [comment]
Can't confirm, this might be an issue with your server software of the client, so please try to update.

But could you please clarify if "createIslandOnJoin" is true or false when this issue occurs?

**Comment by dlsf** [comment]
As this is almost certainly not an issue with our plugin, I'll close this. Please let us know if you are experiencing this problem in the future with the latest Spigot / Paper version and a Vanilla client.
