### ISSUE TITLE
[BUG] Explosions not working

### ISSUE THREAD

**Issue by xiaowine** [IridiumLLC/IridiumSkyblock#548]
No matter whether allowExplosions is true or false, tnt can not destroy the block, the version is paper1.13.2

**Comment by dlsf** [comment]
Are you sure that's an issue with IridiumSkyblock? Do you have any other plugins that might handle explosions?

**Comment by PeachesMLG** [comment]
I already fixed this

**Comment by xiaowine** [comment]
This is my fault
