### ISSUE TITLE
[BUG] Lapis can be sold as Cocoa beans. same for wood

### ISSUE THREAD

**Issue by BoutToBeatMyMeat** [IridiumLLC/IridiumSkyblock#562]
**Describe the bug**
i wanted to sell cocoa beans but i also sold my lapis. same thing for wood. i bought dark wood and sold it at oak wood

**To Reproduce**
1. Go to '/is shop'
2. Click on the 'grassblock'
3. buy dark wood
4. sell oak wood
4. See the mistake

**Console Error**
If applicable, a pastebin link of any console errors
there is no error

**Screenshots**

**Comment by dlsf** [comment]
This is an issue with an old Minecraft version. We recommend you to not use our shop (you can disable it in the config.json) or to update to a newer version.

**Comment by dlsf** [comment]
As we currently don't know if we will support 1.8 - 1.12 in the future, this issue will probably not be resolved.
