### ISSUE TITLE
[BUG] Max archive size - PaperSpigot

### ISSUE THREAD

**Issue by lucas100m** [IridiumLLC/IridiumSkyblock#564]
**Describe the bug**
My server crashed after I tried to use a schematic with 4,801 KB size 

**To Reproduce**
1. Create any big shematic
2. Put in /schematics folder
3. Update the scematics.json
4. Try to make a new island

**Console Error**
https://pastebin.com/4YPEiw6K

**Screenshots**
Not applicable

**Comment by dlsf** [comment]
Are you using Worldedit on your Skyblock server?

**Comment by lucas100m** [comment]
> Are you using Worldedit on your Skyblock server?
FastAsyncWorldEdit-1.16-579

**Comment by dlsf** [comment]
We (currently?) don't support FAWE. Please consider switching to Worldedit for such big schematics.

**Comment by PeachesMLG** [comment]
Ye, because of how fawe works we dont support it (yet)
