### ISSUE TITLE
Island cooldown

### ISSUE THREAD

**Issue by Brunolator** [IridiumLLC/IridiumSkyblock#569]
When i deleted a island because i accidentally placed the water wrong i didn't know that I had to reset it instead of delete it so now I have to wait an hour

**To Reproduce**
1. Make a island
2. Delete the island
3. Try to create another island

**Console Error**
If applicable, a pastebin link of any console errors

**Screenshots**

**Comment by dlsf** [comment]
This is not an issue, but rather a feature to reduce lag. You can adjust the cooldown time in the config.json and bypass the cooldown as an admin with /is bypass. Additionally, you can just right-click with an empty bucket on a block of obsidian and get your lava bucket back so there is no need to reset the island.
