### ISSUE TITLE
[BUG] Island Home

### ISSUE THREAD

**Issue by frendlyZ** [IridiumLLC/IridiumSkyblock#570]
**Describe the bug**
The player is not teleported to the spawn point, where the island was created. After creating an island and using /is home the player is teleported to a different location.

**To Reproduce**
1. Create an island.
2. Use /is home.

**Console Error**
There is no error in the console.

**Comment by dlsf** [comment]
You can adjust the spawn location in the schematics.json, through the values x, y and z. Please be aware that they are offsets from the current spawn location.

**Comment by dlsf** [comment]
Please respond to this issue if you have any further problems, but as I think that this is not a bug, I'll close this issue.
