### ISSUE TITLE
Team join bug

### ISSUE THREAD

**Issue by lowbatman** [IridiumLLC/IridiumSkyblock#60]
Hey,

So I recently just downloaded this plugin on the server, and I noticed something interesting. There is an issue with the island generator in that users cannot invite other users to their islands. When a player is invited to an island and joins, the user cannot see any blocks, move, type or see the chat, and is essentially stuck. 

When the user tries to teleport to their home, this pops up in the console:
22.02 01:25:30 [Server] Server thread/WARN java.lang.NullPointerException

I don't know if this has anything to do with the RAM on my server, but basically, to reproduce them, a player has to basically create their own island or join one. 

![Screenshot (33)](https://user-images.githubusercontent.com/61344390/75088511-07106800-5503-11ea-9215-43a23cdaa47f.png)

Thank you!

**Comment by BGMP** [comment]
@lowbatman What commit are you running on? This used to be an issue some pushes ago
