### ISSUE TITLE
[BUG] Shop Not Working/Cannot Withdraw Money

### ISSUE THREAD

**Issue by leezallen** [IridiumLLC/IridiumSkyblock#61]
I cannot use the internal money system to buy items or withdraw money. I can successfully sell items but if I try to buy some the system tells me that I do not have the funds... Likewise I cannot withdraw money on the bank screen (but I can see my balance). I can withdraw/deposit XP and Stars..

Using Paper 1.14.4 (Build 243)
Iridium Skyblock 2.2.9
Vault 1.7.2

**Comment by insomnia666x** [comment]
i have the same problem, I can withdraw/deposit XP and Stars, but i cant withdraw money!
spigot 1.14.4
iridium skyblock 2.3.0
vault 1.7.3

**Comment by JibarAbardon** [comment]
i have the same problem, I can withdraw/deposit XP and Crystals, but i cant withdraw money!
Paper 1.15.2
iridium skyblock 2.3.1
vault 1.7.2

**Comment by Maks1116** [comment]
I have the same problem.
spigot 1.15.2
