### ISSUE TITLE
Island resets when too many blocks are broken and player dies

### ISSUE THREAD

**Issue by KemsTV** [IridiumLLC/IridiumSkyblock#62]
When player goes to invite to island it gives an internal error msg, even then if I type /is join player I can still join but I noticed that if you break enough blocks, when the player dies the island will reset.

Server log
23.02 04:00:51 [Server] Server thread/INFO aGxInferno issued server command: /is invite KemsTV
23.02 04:00:51 [Server] Server thread/ERROR null
23.02 04:00:51 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin IridiumSkyblock v2.2.9
23.02 04:00:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1607) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1461) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:36) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(SourceFile:9) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:876) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:869) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:852) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:793) [CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.02 04:00:51 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/TextComponent
23.02 04:00:51 [Server] INFO at com.iridium.iridiumskyblock.commands.InviteCommand.execute(InviteCommand.java:38) ~[?:?]
23.02 04:00:51 [Server] INFO at com.iridium.iridiumskyblock.commands.CommandManager.onCommand(CommandManager.java:90) ~[?:?]
23.02 04:00:51 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[CraftBukkit_Latest.jar:git-Bukkit-fba9f48]
23.02 04:00:51 [Server] INFO ... 17 more
23.02 04:00:51 [Server] Server thread/INFO KemsTV issued server command: /is join aGxInferno
23.02 04:01:24 [Server] Netty Epoll Server IO #28/INFO []<KemsTV> test
23.02 04:01:28 [Server] Server thread/INFO aGxInferno tried to swim in lava
23.02 04:01:35 [Server] Server thread/INFO aGxInferno issued server command: /is
23.02 04:01:41 [Server] Server thread/INFO CONSOLE issued server command: /list 
23.02 04:01:41 [Server] Server thread/INFO default: aGxInferno, KemsTV
23.02 04:01:47 [Multicraft] Auto-saving world...
23.02 04:01:47 [Server] Server thread/INFO Saving is already turned on
23.02 04:01:47 [Server] Server thread/INFO Saving the game (this may take a moment!)
23.02 04:01:47 [Server] Server thread/INFO Saved the game
23.02 04:01:51 [Server] Netty Epoll Server IO #28/INFO []<KemsTV> stop test

**Comment by KemsTV** [comment]
Update, So turns out that if you destroy the original spawn block and leave it open for the player to spawn and fall the island will reset. Another fix is to set a new home, then even if the original spawn is destroyed the player will be teleported to the new spawn.

**Comment by BGMP** [comment]
This has to do with the internal logic the server uses to calculate a safe spot for a player to spawn at. To my understanding, it has already been fixed, but I might be wrong on that one. Are you still experiencing this issue? Good thing you've managed to circumvent it by placing some bedrock blocks beneath, but you shouldn't be forced to do so.

**Comment by KemsTV** [comment]
Yea im still having the issue, im not sure how to fix it. Idk if its server
setting either.

**Comment by BGMP** [comment]
@KemsTV It's not a server setting as far as I'm aware of. I have my fork of the Skyblock plugin, and I solved the problem in it, though I can't recall what was causing it x.x.

Also, my fork has some custom things you may not need/want, and is missing some others as well, just to let you know.

**Comment by KemsTV** [comment]
I see, so just sit tight while you work dev magic pretty much? Lol
