### ISSUE TITLE
[BUG]Negative Number of Crystals

### ISSUE THREAD

**Issue by youyoulyz** [IridiumLLC/IridiumSkyblock#69]
Nice plugin! 
But why can players purchase the upgrades though they have fewer crystals than the price I set？
They should have more than the number of crystal as the price to get the upgrade.
Or players will have nagative crystals' number.
Thanks for your hard work.

你好，这是一个很好的插件。
但是有个小小的问题：玩家在升级空岛时，即使他们的水晶不足以升级，他们的空岛依然会升级成功，玩家的水晶会被扣成负数。希望要求玩家在升级空岛时，不能赊账或者贷款，必须水晶满足升级的代价的时候才能升级。
谢谢你的付出！

**Comment by lightlessfilms** [comment]
I can reproduce this bug. This totally breaks this plugin.
If you have negative crystals, you can then go the bank and collect the negative crystals. This results in the bank going to 0 crystals. After this you can buy 1 upgrade and repeat the previous step going in a loop.

which totally breaks the game and plugin
