### ISSUE TITLE
[BUG] Miner and Farmer mission not counting

### ISSUE THREAD

**Issue by JayJay1989** [IridiumLLC/IridiumSkyblock#81]
**Describe the bug**
For some reason farmer and miner missions are not counting blocks and crops

Server: paper 1.15.2-161

**To Reproduce**
1. Mine blocks / harvest crops
2. mission doesn't increase

**Screenshots**
https://img.lateur.pro/slbm43.png > miner mission
https://img.lateur.pro/9b3od7.png > farmer mission

**Comment by makkurattv** [comment]
Currently having the same issue as well. I even update my statz placeholders hoping that could help and it is still persisting.

**Comment by makkurattv** [comment]
I have made progress with farmer, but I found a fix for the miner progression not going up. Go to your plugins folder, IridiumSkyblock folder, missions.json, and search for "miner". All the ores are typed as "Coal Ore" or "Diamond Ore" and they must be changed to "COAL_ORE" and "DIAMOND_ORE" respectively. You must make sure they are all caps and  that it matches the item's id.

**Comment by IridiumLLC** [comment]
Made these default changes to missions.json
