### ISSUE TITLE
[BUG]Use Dirt to Increase Skyblock Value

### ISSUE THREAD

**Issue by youyoulyz** [IridiumLLC/IridiumSkyblock#84]
When a player place a dirt onto his island, his island's value will increase.
If the player cultivate the dirt into an arrable-land, his value will not decrease.
If the player remove the arrable-land, its value will not decrease.
In this way, the island value can be created enormously fast.
Hope you can solve this problem.

**Comment by IridiumLLC** [comment]
not quite sure what you mean? Could you record a video for me and send me your blockvalues.json?

**Comment by youyoulyz** [comment]
[](http://mcyouyou.qicp.vip:233/res/bandicam%202020-04-10%2018-08-42-977.avi)
The video is provided here.
It can be solved by setting the price of arrable_land.

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there
