### ISSUE TITLE
[BUG] Spawner break bug

### ISSUE THREAD

**Issue by dieterblancke** [IridiumLLC/IridiumSkyblock#87]
**Describe the bug**
When people place a spawner and break it again, the value of the spawner never gets discounted from the island level.

Our config:
```json
{
  "blockvalue": {
    "LAPIS_BLOCK": 1.0,
    "BEACON": 25.0,
    "DIAMOND_BLOCK": 4.0,
    "REDSTONE_BLOCK": 1.0,
    "IRON_BLOCK": 3.0,
    "SPAWNER": 10.0,
    "GOLD_BLOCK": 3.0,
    "EMERALD_BLOCK": 5.0
  },
  "spawnervalue": {
    "BLAZE": 60.0,
    "COW": 50.0,
    "IRON_GOLEM": 60.0,
    "PIG": 50.0
  }
}
```

To reproduce, just place a spawner that has a value and try to remove it again.
I haven't looked much, but it might be related to this line:
https://github.com/IridiumLLC/IridiumSkyblock/blob/master/src/main/java/com/iridium/iridiumskyblock/listeners/onBlockBreak.java#L54

**Comment by IridiumLLC** [comment]
Thought I removed that line, ill do that now. Should fix the issue. also you shouldn't have
    "SPAWNER": 10.0,
in the blocks file
