### ISSUE TITLE
[BUG] Iron Blocks remain in island value after making an iron golem

### ISSUE THREAD

**Issue by Erorserv** [IridiumLLC/IridiumSkyblock#98]
When making an iron golem, the island value gained will remain even after the golem is created and has died.

**To Reproduce**
1. View your island value
2. Create an iron golem
3. View island value 
4. Kill the iron golem
5. View island value

**Comment by IridiumLLC** [comment]
Should be fixed. Look in the discord pinned messages I linked a beta-version for it there
